import { applyFunction, ClassDef } from "./tools";

export const httpClass: ClassDef = {
    name: "http.Http",
    methods: [
        {
            label: "Get",
            type: "method",
            info: "Make GET request",
            detail: "Get(url: string) => any",
            apply: applyFunction('Get("https://api.example.com")', 5, 28),
            returnType: "any",
            source: "osi4iot",
        },
        {
            label: "GetWithJwt",
            type: "method",
            info: "Make GET request with JWT",
            detail: "GetWithJwt(url: string, token: string) => any",
            apply: applyFunction('GetWithJwt("https://api.example.com", "your_jwt_token")', 12, 35),
            returnType: "any",
            source: "osi4iot",
        },
        {
            label: "Post",
            type: "method",
            info: "Make POST request",
            detail: "Post(url: string, data: any) => any",
            apply: applyFunction('Post("https://api.example.com", data)', 6, 29),
            returnType: "any",
            source: "osi4iot",
        },
        {
            label: "PostWithJwt",
            type: "method",
            info: "Make POST request with JWT",
            detail: "PostWithJwt(url: string, data: any, token: string) => any",
            apply: applyFunction('PostWithJwt("https://api.example.com", data, "your_jwt_token")', 13, 36),
            returnType: "any",
            source: "osi4iot",
        },
        {
            label: "Patch",
            type: "method",
            info: "Make PATCH request",
            detail: "Patch(url: string, data: any) => any",
            apply: applyFunction('Patch("https://api.example.com", data)', 7, 30),
            returnType: "any",
            source: "osi4iot",
        },
        {
            label: "PatchWithJwt",
            type: "method",
            info: "Make PATCH request with JWT",
            detail: "PatchWithJwt(url: string, data: any, token: string) => any",
            apply: applyFunction('PatchWithJwt("https://api.example.com", data, "your_jwt_token")', 14, 37),
            returnType: "any",
            source: "osi4iot",
        },
        {
            label: "Delete",
            type: "method",
            info: "Make DELETE request",
            detail: "Delete(url: string) => any",
            apply: applyFunction('Delete("https://api.example.com")', 8, 31),
            returnType: "any",
            source: "osi4iot",
        },
        {
            label: "DeleteWithJwt",
            type: "method",
            info: "Make DELETE request with JWT",
            detail: "DeleteWithJwt(url: string, token: string) => any",
            apply: applyFunction('DeleteWithJwt("https://api.example.com", "your_jwt_token")', 15, 38),
            returnType: "any",
            source: "osi4iot",
        },
    ],
    instances: [
        {
            label: "http",
            declaration: "const http = go.Http()",
            insert: "http = go.Http();",
            info: "Create HTTP instance",
        },
    ],
};
