import { applyFunction, ClassDef } from "./utils";

export const kvStoreClass: ClassDef = {
    name: "KvStore",
    methods: [
        {
            label: "SetValue",
            type: "method",
            info: "Set a value in the KV store",
            detail: "(key: string, value: any) => void",
            apply: applyFunction('SetValue("key", "value");', 10, 13),
            returnType: undefined,
            source: "osi4iot",
        },
        {
            label: "GetNumberValue",
            type: "method",
            info: "Get a number value from the KV store",
            detail: "(key: string) => number",
            apply: applyFunction('GetNumberValue("key");', 16, 19),
            returnType: "number",
            source: "osi4iot",
        },
        {
            label: "GetStringValue",
            type: "method",
            info: "Get a string value from the KV store",
            detail: "(key: string) => string",
            apply: applyFunction('GetStringValue("key");', 16, 19),
            returnType: "string",
            source: "osi4iot",
        },
        {
            label: "GetBooleanValue",
            type: "method",
            info: "Get a boolean value from the KV store",
            detail: "(key: string) => boolean",
            apply: applyFunction('GetBooleanValue("key");', 17, 20),
            returnType: "boolean",
            source: "osi4iot",
        },
        {
            label: "GetArrayValue",
            type: "method",
            info: "Get an array value from the KV store",
            detail: "(key: string) => Array<any>",
            apply: applyFunction('GetArrayValue("key");', 15, 18),
            returnType: "Array<any>",
            source: "osi4iot",
        },
        {
            label: "GetObjectValue",
            type: "method",
            info: "Get an object value from the KV store",
            detail: "(key: string) => Object",
            apply: applyFunction('GetObjectValue("key");', 16, 19),
            returnType: "Object",
            source: "osi4iot",
        },
        {
            label: "DeleteEntry",
            type: "method",
            info: "Delete a value from the KV store",
            detail: "(key: string) => void",
            apply: applyFunction('DeleteEntry("key");', 13, 16),
            returnType: undefined,
            source: "osi4iot",
        },
        {
            label: "DeleteAllEntries",
            type: "method",
            info: "Delete all entries from the KV store",
            detail: "(key: string) => void",
            apply: applyFunction('DeleteAllEntries("key");', 18, 21),
            returnType: undefined,
            source: "osi4iot",
        },
        {
            label: "ExistsKey",
            type: "method",
            info: "Check if a key exists in the KV store",
            detail: "(key: string) => boolean",
            apply: applyFunction('ExistsKey("key");', 11, 14),
            returnType: "boolean",
            source: "osi4iot",
        },
        {
            label: "ListKeys",
            type: "method",
            info: "List all keys in the KV store",
            detail: "() => Array<string>",
            apply: "ListKeys()",
            returnType: "Array<string>",
            source: "osi4iot",
        },
    ],
    instances: [
        {
            label: "kvStore",
            declaration: "const kvStore = go.KvStore()",
            insert: "kvStore = go.KvStore();",
            info: "Create KVStore instance",
        },
    ],
};
