# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
FROM python:3.11-alpine

# Install build dependencies
RUN apk add --no-cache build-base

WORKDIR /app

# Copy project files into the container
COPY . .

# Upgrade pip and install the project with its dependencies
RUN pip install --upgrade pip \
    && pip install .

# Expose port if needed (not required for mcp via stdio)

# Run the MCP server
CMD ["python", "server.py"]
