import crypto from "crypto";
import process_env from "../../config/api_config";

// AES-256-GCM: confidentiality AND integrity. Any change to the stored
// ciphertext, IV or tag makes decrypt() throw instead of returning
// silently altered text.
const ALGORITHM = "aes-256-gcm";

// 96-bit IV, the size GCM is designed for.
const IV_LENGTH = 12;

// Full 128-bit authentication tag. Checked explicitly on decrypt so a
// truncated tag (easier to forge) is never accepted.
const TAG_LENGTH = 16;

// Format version stored with every value, so the scheme can evolve
// later without guessing how an old record was written.
const FORMAT_VERSION = 2;

// ENCRYPTION_SECRET_KEY is 32 random bytes, hex encoded (64 characters),
// generated by the platform CLI with crypto/rand. It is decoded to raw
// bytes and used as the key directly — not used as text, which would
// limit it to the ~6 bits per character of its alphabet.
//
// Checked once at startup: a missing or malformed key must stop
// admin_api right away, not surface as a failure on the first secret
// someone tries to read.
const loadKey = (): Buffer => {
	const hex = process_env.ENCRYPTION_SECRET_KEY ?? "";
	if (!/^[0-9a-fA-F]{64}$/.test(hex)) {
		throw new Error(
			"ENCRYPTION_SECRET_KEY must be 64 hexadecimal characters (32 random bytes)"
		);
	}
	return Buffer.from(hex, "hex");
};

const key = loadKey();

interface EncryptedPayload {
	v: number;
	iv: string;
	tag: string;
	content: string;
}

/**
 * Encrypts text for storage in the database.
 *
 * A new random IV is generated on EVERY call. Reusing an IV with the
 * same key must never happen: with GCM (as with the previous CTR mode)
 * it exposes the keystream — anyone knowing one plaintext could then
 * decrypt the others — and it also breaks GCM's authentication.
 *
 * `context` is optional associated data: authenticated but not stored.
 * Pass something that identifies where the value belongs (e.g.
 * `org:${orgId}:device:${deviceId}`) and decrypt() must be given the
 * same value, so a ciphertext copied into another row or organization
 * fails to decrypt instead of being accepted there.
 */
export const encrypt = (text: string, context?: string): string => {
	const iv = crypto.randomBytes(IV_LENGTH);
	const cipher = crypto.createCipheriv(ALGORITHM, key, iv, { authTagLength: TAG_LENGTH });
	if (context !== undefined) {
		cipher.setAAD(Buffer.from(context, "utf8"));
	}
	const content = Buffer.concat([cipher.update(text, "utf8"), cipher.final()]);

	const payload: EncryptedPayload = {
		v: FORMAT_VERSION,
		iv: iv.toString("hex"),
		tag: cipher.getAuthTag().toString("hex"),
		content: content.toString("hex"),
	};
	return Buffer.from(JSON.stringify(payload), "utf8").toString("base64");
};

/**
 * Decrypts a value produced by encrypt(). Throws if the value is not in
 * the current format, was tampered with, or was encrypted with a
 * different key or `context`.
 */
export const decrypt = (encryptedText: string, context?: string): string => {
	let payload: EncryptedPayload;
	try {
		payload = JSON.parse(Buffer.from(encryptedText, "base64").toString("utf8"));
	} catch {
		throw new Error("encrypted value is not valid base64-encoded JSON");
	}

	if (payload.v !== FORMAT_VERSION) {
		// Values written by the old AES-256-CTR scheme carry no version.
		// They are not readable with the new key and must be stored again.
		throw new Error(
			`unsupported encrypted value format (v=${payload.v ?? "none"}); ` +
				"values from the previous scheme have to be re-entered"
		);
	}

	const iv = Buffer.from(payload.iv, "hex");
	const tag = Buffer.from(payload.tag, "hex");
	if (iv.length !== IV_LENGTH) {
		throw new Error("invalid IV length in encrypted value");
	}
	if (tag.length !== TAG_LENGTH) {
		throw new Error("invalid authentication tag length in encrypted value");
	}

	const decipher = crypto.createDecipheriv(ALGORITHM, key, iv, { authTagLength: TAG_LENGTH });
	decipher.setAuthTag(tag);
	if (context !== undefined) {
		decipher.setAAD(Buffer.from(context, "utf8"));
	}

	try {
		return Buffer.concat([
			decipher.update(Buffer.from(payload.content, "hex")),
			decipher.final(), // verifies the tag
		]).toString("utf8");
	} catch {
		// Same message for every cause on purpose: wrong key, wrong
		// context and tampering are indistinguishable to GCM, and the
		// caller must not learn which it was.
		throw new Error("encrypted value could not be authenticated");
	}
};