export const timezoneOptions = [
    { value: "America/New_York", label: "America/New_York" },
    { value: "America/Chicago", label: "America/Chicago" },
    { value: "America/Denver", label: "America/Denver" },
    { value: "America/Los_Angeles", label: "America/Los_Angeles" },
    { value: "America/Mexico_City", label: "America/Mexico_City" },
    { value: "America/Bogota", label: "America/Bogota" },
    { value: "America/Sao_Paulo", label: "America/Sao_Paulo" },
    { value: "America/Argentina/Buenos_Aires", label: "America/Argentina/Buenos_Aires" },
    { value: "Europe/London", label: "Europe/London" },
    { value: "Europe/Madrid", label: "Europe/Madrid" },
    { value: "Europe/Paris", label: "Europe/Paris" },
    { value: "Europe/Berlin", label: "Europe/Berlin" },
    { value: "Europe/Moscow", label: "Europe/Moscow" },
    { value: "Asia/Tokyo", label: "Asia/Tokyo" },
    { value: "Asia/Shanghai", label: "Asia/Shanghai" },
    { value: "Asia/Kolkata", label: "Asia/Kolkata" },
    { value: "Asia/Singapore", label: "Asia/Singapore" },
    { value: "Asia/Dubai", label: "Asia/Dubai" },
    { value: "Australia/Sydney", label: "Australia/Sydney" },
    { value: "Pacific/Auckland", label: "Pacific/Auckland" },
    { value: "Africa/Cairo", label: "Africa/Cairo" },
    { value: "Africa/Johannesburg", label: "Africa/Johannesburg" },
    { value: "Africa/Lagos", label: "Africa/Lagos" },
];