DO $$
BEGIN
   IF NOT EXISTS (SELECT FROM pg_roles WHERE rolname = 'grafanadb') THEN
      CREATE ROLE grafanadb LOGIN PASSWORD '${GRAFANA_DB_PASSWORD}';
   END IF;

   IF NOT EXISTS (SELECT FROM pg_roles WHERE rolname = '${SUPERADMIN_USER}') THEN
      CREATE ROLE ${SUPERADMIN_USER} WITH LOGIN PASSWORD '${SUPERADMIN_PASSWORD}' SUPERUSER;
   END IF;

END
$$;
CREATE SCHEMA IF NOT EXISTS AUTHORIZATION grafanadb;
REVOKE ALL ON SCHEMA public FROM public;

