import { applyFunction, ClassDef } from "../tools";

export const imageRectangleClass: ClassDef = {
    name: "image.Rectangle",
    methods: [
        {
            label: "Add",
            type: "method",
            info: "Returns the rectangle r translated by p.",
            detail: "(p image.Point) => image.Rectangle",
            apply: applyFunction("Add(p)", 4, 5),
            returnType: "image.Rectangle",
            source: "go_method",
        },
        {
            label: "At",
            type: "method",
            info: "Returns the color of the pixel at (x, y) in the rectangle.",
            detail: "(x, y int) => color.Color",
            apply: applyFunction("At(x, y)", 4, 5),
            returnType: "color.Color",
            source: "go_method",
        },
        {
            label: "Bounds",
            type: "method",
            info: "Returns the bounds of the image.",
            detail: "() => image.Rectangle",
            apply: "Bounds()",
            returnType: "image.Rectangle",
            source: "go_method",
        },
        {
            label: "Canon",
            type: "method",
            info: "Returns the  the canonical version of r. The returned rectangle has minimum and maximum coordinates swapped if necessary so that it is well-formed.",
            detail: "() => image.Rectangle",
            apply: "Canon()",
            returnType: "image.Rectangle",
            source: "go_method",
        },
        {
            label: "ColorModel",
            type: "method",
            info: "Returns the color model of the image.",
            detail: "() => color.Model",
            apply: "ColorModel()",
            returnType: "color.Model",
            source: "go_method",
        },
        {
            label: "Dx",
            type: "method",
            info: "Returns the width of the rectangle.",
            detail: "() => int",
            apply: "Dx()",
            returnType: "int",
            source: "go_method",
        },
        {
            label: "Dy",
            type: "method",
            info: "Returns the height of the rectangle.",
            detail: "() => int",
            apply: "Dy()",
            returnType: "int",
            source: "go_method",
        },
        {
            label: "Empty",
            type: "method",
            info: "Reports whether the rectangle contains no points.",
            detail: "() => int",
            apply: "Empty()",
            returnType: "int",
            source: "go_method",
        },
        {
            label: "Eq(s Rectangle) bool",
            type: "method",
            info: "Reports whether r and s contain the same set of points. All empty rectangles are considered equal.",
            detail: "(s Rectangle) => bool",
            apply: applyFunction("Eq(s)", 3, 4),
            returnType: "bool",
            source: "go_method",
        },
        {
            label: "In",
            type: "method",
            info: "Returns whether this Point is inside the given Rectangle.",
            detail: "(r Rectangle) => bool",
            apply: applyFunction("In(r)", 3, 4),
            returnType: "bool",
            source: "go_method",
        },
        {
            label: "Inset",
            type: "method",
            info: "Returns a new Rectangle that is inset by the given amount.",
            detail: "(n int) => image.Rectangle",
            apply: applyFunction("Inset(n)", 6, 7),
            returnType: "image.Rectangle",
            source: "go_method",
        },
        {
            label: "Intersect",
            type: "method",
            info: "Returns the largest rectangle contained by both r and s. If the two rectangles do not overlap then the zero rectangle will be returned. the largest rectangle contained by both r and s. If the two rectangles do not overlap then the zero rectangle will be returned.",
            detail: "(s Rectangle) => image.Rectangle",
            apply: applyFunction("Intersect(s)", 6, 7),
            returnType: "image.Rectangle",
            source: "go_method",
        },
        {
            label: "Overlaps(s Rectangle) bool",
            type: "method",
            info: "Reports whether the given rectangle and s have a non-empty intersection.",
            detail: "(s Rectangle) => bool",
            apply: applyFunction("Overlaps(s)", 9, 10),
            returnType: "bool",
            source: "go_method",
        },
        {
            label: "RGBA64At",
            type: "method",
            info: "Returns the RGBA64 color value at the specified coordinates.",
            detail: "(x, y int) => color.RGBA64",
            apply: applyFunction("RGBA64At(x, y)", 12, 13),
            returnType: "color.RGBA64",
            source: "go_method",
        },
        {
            label: "Size",
            type: "method",
            info: "Return the width and height of the given rectangle.",
            detail: "() => image.Point",
            apply: "Size()",
            returnType: "image.Point",
            source: "go_method",
        },
        {
            label: "String",
            type: "method",
            info: "Return the string representation of the given rectangle like (3,4)-(6,5).",
            detail: "() => string",
            apply: applyFunction("String()", 5, 6),
            returnType: "string",
            source: "go_method",
        },
        {
            label: "Union(s Rectangle) Rectangle",
            type: "method",
            info: "Returns the smallest rectangle that contains both the given rectangle and s.",
            detail: "(s Rectangle) => image.Rectangle",
            apply: applyFunction("Union(s)", 6, 7),
            returnType: "image.Rectangle",
            source: "go_method",
        },
    ],
    instances: [],
};
