import { applyFunction, ClassDef } from "../tools";

export const imagePointClass: ClassDef = {
    name: "image.Point",
    methods: [
        {
            label: "Pt",
            type: "method",
            info: "Returns a new Point with the specified coordinates.",
            detail: "(x, y int) => image.Point",
            apply: applyFunction("Pt(x, y)", 3, 4),
            returnType: "image.Point",
            source: "go_method",
        },
        {
            label: "Add",
            type: "method",
            info: "Returns a new Point that is the sum of this Point and another Point.",
            detail: "(q image.Point) => image.Point",
            apply: applyFunction("Add(q)", 4, 5),
            returnType: "image.Point",
            source: "go_method",
        },
        {
            label: "Div",
            type: "method",
            info: "Returns a new Point that is the result of dividing this Point by a scalar.",
            detail: "(k int) => image.Point",
            apply: applyFunction("Div(k)", 5, 6),
            returnType: "image.Point",
            source: "go_method",
        },
        {
            label: "Eq",
            type: "method",
            info: "Returns whether this Point is equal to another Point.",
            detail: "(q Point) => bool",
            apply: applyFunction("Eq(q)", 3, 4),
            returnType: "bool",
            source: "go_method",
        },
        {
            label: "In",
            type: "method",
            info: "Returns whether this Point is inside the given Rectangle.",
            detail: "(r Rectangle) => bool",
            apply: applyFunction("In(r)", 3, 4),
            returnType: "bool",
            source: "go_method",
        },
        {
            label: "Mod",
            type: "method",
            info: "Returns the point q in r such that p.X-q.X is a multiple of r's width and p.Y-q.Y is a multiple of r's height.",
            detail: "(r Rectangle) => image.Point",
            apply: applyFunction("Mod(r)", 4, 5),
            returnType: "image.Point",
            source: "go_method",
        },
        {
            label: "Mul",
            type: "method",
            info: "Returns a new Point that is the result of multiplying this Point by a scalar.",
            detail: "(k int) => image.Point",
            apply: applyFunction("Mul(k)", 4, 5),
            returnType: "image.Point",
            source: "go_method",
        },
        {
            label: "String",
            type: "method",
            info: "Return the string representation of the Point.",
            detail: "() => string",
            apply: applyFunction("String()", 5, 6),
            returnType: "string",
            source: "go_method",
        },
        {
            label: "Sub",
            type: "method",
            info: "Returns a new Point that is the result of subtracting another Point from this Point.",
            detail: "(q Point) => image.Point",
            apply: applyFunction("Sub(q)", 4, 5),
            returnType: "image.Point",
            source: "go_method",
        },        
    ],
    instances: [],
};
