import { applyFunction, ClassDef } from "../tools";

export const imageUniformClass: ClassDef = {
    name: "image.Uniform",
    methods: [
        {
            label: "At",
            type: "method",
            info: "Returns the color value at the specified coordinates.",
            detail: "(x, y int) => color.Color",
            apply: applyFunction("At(x, y)", 3, 4),
            returnType: "color.Color",
            source: "go_method",
        },
        {
            label: "Bounds()",
            type: "method",
            info: "Returns the bounds of the image.",
            detail: "() => image.Rectangle",
            apply: "Bounds()",
            returnType: "image.Rectangle",
            source: "go_method",
        },
        {
            label: "ColorModel",
            type: "method",
            info: "Returns the color model of the image.",
            detail: "() => color.Model",
            apply: "ColorModel()",
            returnType: "color.Model",
            source: "go_method",
        },
        {
            label: "Convert",
            type: "method",
            info: "Converts the given color to the image's color model.",
            detail: "(c color.Color) => color.Color",
            apply: applyFunction("Convert(c)", 8, 9),
            returnType: "color.Color",
            source: "go_method",
        },
        {
            label: "Opaque",
            type: "method",
            info: "Returns whether the image is opaque.",
            detail: "() => bool",
            apply: "Opaque()",
            returnType: "bool",
            source: "go_method",
        },
        {
            label: "RGBA() (r, g, b, a uint32)",
            type: "method",
            info: "Returns the constant color of the image in the pre-multiplied RGBA format using the color.Color interface.",
            detail: "() => (r, g, b, a uint32)",
            apply: "RGBA()",
            returnType: "[]uint32",
            source: "go_method",
        },
        {
            label: "RGBA64At",
            type: "method",
            info: "Returns the RGBA64 color value at the specified coordinates.",
            detail: "(x, y int) => color.RGBA64",
            apply: applyFunction("RGBA64At(x, y)", 12, 13),
            returnType: "color.RGBA64",
            source: "go_method",
        },
    ],
    instances: [],
};