import { applyFunction, ClassDef } from "../tools";

export const imageNYCbCrAClass: ClassDef = {
    name: "image.NYCbCrA",
    methods: [
        {
            label: "AOffset(x, y int) int",
            type: "method",
            info: "Returns the alpha offset at the specified coordinates.",
            detail: "(x, y int) => int",
            apply: applyFunction("AOffset(x, y)", 8, 9),
            returnType: "int",
            source: "go_method",
        },
        {
            label: "At",
            type: "method",
            info: "Returns the bounds of the image.",
            detail: "(x, y int) => color.Color",
            apply: applyFunction("At(x, y)", 3, 4),
            returnType: "color.Color",
            source: "go_method",
        },
        {
            label: "ColorModel",
            type: "method",
            info: "Returns the color model of the image.",
            detail: "() => color.Model",
            apply: "ColorModel()",
            returnType: "color.Model",
            source: "go_method",
        },
        {
            label: "NYCbCrAAt",
            type: "method",
            info: "Returns the NYCbCrA color value at the specified coordinates.",
            detail: "(x, y int) => color.NYCbCrA",
            apply: applyFunction("NYCbCrAAt(x, y)", 10, 11),
            returnType: "color.NYCbCrA",
            source: "go_method",
        },
        {
            label: "Opaque",
            type: "method",
            info: "Returns whether the image is opaque.",
            detail: "() => bool",
            apply: "Opaque()",
            returnType: "bool",
            source: "go_method",
        },
        {
            label: "RGBA64At",
            type: "method",
            info: "Returns the RGBA64 color value at the specified coordinates.",
            detail: "(x, y int) => color.RGBA64",
            apply: applyFunction("RGBA64At(x, y)", 12, 13),
            returnType: "color.RGBA64",
            source: "go_method",
        },
        {
            label: "SubImage",
            type: "method",
            info: "Returns a sub-image defined by the specified rectangle.",
            detail: "(r Rectangle) => image.Image",
            apply: applyFunction("SubImage(r)", 9, 10),
            returnType: "Image",
            source: "go_method",
        },
    ],
    instances: [],
};
