import { applyFunction, ClassDef } from "../tools";

export const imageClass: ClassDef = {
    name: "image.Image",
    methods: [
        {
            label: "Black",
            type: "constant",
            info: "",
            detail: "It is an opaque black uniform image.",
            apply: "Black",
            returnType: "image.Uniform",
            source: "go_constant",
        }, 
        {
            label: "Opaque",
            type: "constant",
            info: "",
            detail: "It is a fully opaque uniform image.",
            apply: "Opaque",
            returnType: "image.Uniform",
            source: "go_constant",
        },
        {
            label: "Transparent",
            type: "constant",
            info: "",
            detail: "It is a fully transparent uniform image.",
            apply: "Transparent",
            returnType: "image.Uniform",
            source: "go_constant",
        },
        {
            label: "White",
            type: "constant",
            info: "",
            detail: "It is an opaque white uniform image.",
            apply: "White",
            returnType: "image.Uniform",
            source: "go_constant",
        },
        {
            label: "Draw",
            type: "method",
            info: "Draw draws the source image src onto the destination image dst using the specified rectangle r, point sp, and compositing operator op.",
            detail: "(dst draw.Image, r image.Rectangle, src image.Image, sp image.Point, op draw.Op) => void",
            apply: applyFunction("Draw(dst, r, src, sp, op)", 5, 8),
            returnType: "void",
            source: "go_function",
        },
        {
            label: "DrawMask(dst draw.Image, r image.Rectangle, src image.Image, sp image.Point, mask image.Image, mp image.Point, op draw.Op)",
            type: "method",
            info: "DrawMask draws the source image src onto the destination image dst using the specified rectangle r, point sp, and compositing operator op, while applying the mask image.",
            detail: "(dst draw.Image, r image.Rectangle, src image.Image, sp image.Point, mask image.Image, mp image.Point, op draw.Op) => void",
            apply: applyFunction("DrawMask(dst, r, src, sp, mask, mp, op)", 9, 12),
            returnType: "void",
            source: "go_function",
        },
        {
            label: "NewAlpha",
            type: "method",
            info: "Create a new alpha channel image with 8 bits per pixel.",
            detail: "(r image.Rectangle) => *image.Alpha",
            apply: applyFunction("NewAlpha(r)", 9, 10),
            returnType: "image.Alpha",
            source: "go_function",
        },
        {
            label: "NewAlpha16",
            type: "method",
            info: "Create a new alpha channel image with 16 bits per pixel.",
            detail: "(r image.Rectangle) => *image.Alpha16",
            apply: applyFunction("NewAlpha16(r)", 11, 12),
            returnType: "image.Alpha16",
            source: "go_function",
        },
        {
            label: "NewCMYK",
            type: "method",
            info: "Create a new image with Cyan, Magenta, Yellow, and Black color channels, 8 bits each.",
            detail: "(r image.Rectangle) => *image.CMYK",
            apply: applyFunction("NewCMYK(r)", 11, 12),
            returnType: "image.CMYK",
            source: "go_function",
        },
        {
            label: "NewGray",
            type: "method",
            info: "Create a new grayscale image with 8 bits per pixel.",
            detail: "(r image.Rectangle) => *image.Gray",
            apply: applyFunction("NewGray(r)", 8, 9),
            returnType: "image.Gray",
            source: "go_function",
        },
        {
            label: "NewGray16",
            type: "method",
            info: "Create a new grayscale image with 16 bits per pixel.",
            detail: "(r image.Rectangle) => *image.Gray16",
            apply: applyFunction("NewGray16(r)", 10, 11),
            returnType: "image.Gray16",
            source: "go_function",
        },
        {
            label: "NewNRGBA",
            type: "method",
            info: "Create a new NRGBA image with 8 bits per channel (32 bits per pixel).",
            detail: "(r image.Rectangle) => *image.NRGBA",
            apply: applyFunction("NewNRGBA(r)", 9, 10),
            returnType: "image.NRGBA",
            source: "go_function",
        },
        {
            label: "NewNRGBA64",
            type: "method",
            info: "Create a new NRGBA image with 16 bits per channel (64 bits per pixel).",
            detail: "(r image.Rectangle) => *image.NRGBA64",
            apply: applyFunction("NewNRGBA64(r)", 11, 12),
            returnType: "image.NRGBA64",
            source: "go_function",
        },
        {
            label: "NewNYCbCrA",
            type: "method",
            info: "Create a new YCbCr image with 8 bits per channel (24 bits per pixel).",
            detail: "(r image.Rectangle, subsampleRatio image.YCbCrSubsampleRatio) => *image.NYCbCrA",
            apply: applyFunction("NewNYCbCrA(r, subsampleRatio)", 11, 12),
            returnType: "image.NYCbCrA",
            source: "go_function",
        },
        {
            label: "NewPaletted",
            type: "method",
            info: "Create a new paletted image with the given rectangle and color palette.",
            detail: "(r image.Rectangle, p color.Palette) => *image.Paletted",
            apply: applyFunction("NewPaletted(r, p)", 12, 13),
            returnType: "image.Paletted",
            source: "go_function",
        },
        {
            label: "NewRGBA",
            type: "method",
            info: "Create a new RGBA image with the given rectangle and 8 bits per channel.",
            detail: "(r image.Rectangle) => *image.RGBA",
            apply: applyFunction("NewRGBA(r)", 8, 9),
            returnType: "image.RGBA",
            source: "go_function",
        },
        {
            label: "NewRGBA64",
            type: "method",
            info: "Create a new RGBA image with the given rectangle and 16 bits per channel.",
            detail: "(r image.Rectangle) => *image.RGBA64",
            apply: applyFunction("NewRGBA64(r)", 10, 11),
            returnType: "image.RGBA64",
            source: "go_function",
        },
        {
            label: "NewUniform",
            type: "method",
            info: "Create a new uniform image with the given rectangle and 16 bits per channel.",
            detail: "(c color.Color) => *image.Uniform",
            apply: applyFunction("NewUniform(c)", 11, 12),
            returnType: "image.Uniform",
            source: "go_function",
        },
        {
            label: "NewYCbCr",
            type: "method",
            info: "Create a new YCbCr image with the given rectangle and subsample ratio.",
            detail: "(r image.Rectangle, subsampleRatio image.YCbCrSubsampleRatio) => *image.YCbCr",
            apply: applyFunction("NewYCbCr(r, subsampleRatio)", 9, 10),
            returnType: "image.YCbCr",
            source: "go_function",
        },
        {
            label: "Point(x, y int) image.Point",
            type: "method",
            info: "Create a new point with the given coordinates.",
            detail: "(x, y int) => image.Point",
            apply: applyFunction("Point(x, y)", 6, 7),
            returnType: "image.Point",
            source: "go_function",
        },
        {
            label: "Rect",
            type: "method",
            info: "Create a new rectangle with the given coordinates.",
            detail: "(x0, y0, x1, y1 int) => image.Rectangle",
            apply: applyFunction("Rect(x0, y0, x1, y1)", 5, 7),
            returnType: "image.Rectangle",
            source: "go_function",
        },
        {
            label: "Resize",
            type: "method",
            info: "Resize the image to the specified width and height using the given interpolation function.",
            detail: "(pic image.Image, width uint, height uint, interp resize.InterpolationFunction) => image.Image",
            apply: applyFunction("Resize(pic, width, height, interp)", 7, 10),
            returnType: "image.Image",
            source: "go_function",
        },
        {
            label: "Thumbnail",
            type: "method",
            info: "Thumbnail will downscale provided image to max width and height preserving original aspect ratio and using the interpolation function interp. It will return original image, without processing it, if original sizes are already smaller than provided constraints.",
            detail: "(maxWidth, maxHeight uint, src image.Image, interp resize.InterpolationFunction) => image.Image",
            apply: applyFunction("Thumbnail(maxWidth, maxHeight, src, interp)", 10, 18),
            returnType: "image.Image",
            source: "go_function",
        },
        {
            label: "DecodeImageFromBase64",
            type: "method",
            info: "Decode a base64-encoded image.",
            detail: "(base64String: string) => Image",
            apply: applyFunction("DecodeImageFromBase64(base64String)", 22, 34),
            returnType: "image.Image",
            source: "osi4iot",
        },
        {
            label: "DecodeImageFromFile",
            type: "method",
            info: "Decode an image from a file.",
            detail: "(filename string) => Image",
            apply: applyFunction("DecodeImageFromFile(filename)", 20, 28),
            returnType: "image.Image",
            source: "osi4iot",
        },                
        {
            label: "EncodeImageToBase64",
            type: "method",
            info: "Encode an image to a base64 string.",
            detail: "(pic image.Image, format string, quality int) => string",
            apply: applyFunction('EncodeImageToBase64(pic, "png", 90)', 20, 23),
            returnType: "string",
            source: "osi4iot",
        },
        {
            label: "EncodeImageToFile",
            type: "method",
            info: "Encode an image to a file.",
            detail: "(filename string, format string, src image.Image)",
            apply: applyFunction('EncodeImageToFile("output.png", "png", pic)', 19, 29),
            returnType: "void",
            source: "osi4iot",
        },
        {
            label: "GetDrawOp",
            type: "method",
            info: "GetDrawOp returns the Porter-Duff compositing operator corresponding to the given string.",
            detail: "(opName string) => draw.Op",
            apply: applyFunction("GetDrawOp(opName)", 10, 16),
            returnType: "draw.Op",
            source: "osi4iot",
        },
        {
            label: "GetInterpolationFunction",
            type: "method",
            info: "Get the interpolation function based on the method name.",
            detail: "(method string) => resize.InterpolationFunction",
            apply: applyFunction("GetInterpolationFunction(method)", 25, 31),
            returnType: "resize.InterpolationFunction",
            source: "osi4iot",
        },
        {
            label: "PixelsConvertion",
            type: "method",
            info: "Convert image pixels to a float32 array.",
            detail: "(pic image.Image, channelSize int, imgWidth int, imgHeight int) => []float32",
            apply: applyFunction("PixelsConvertion(pic, channelSize, imgWidth, imgHeight)", 17, 20),
            returnType: "[]float32",
            source: "osi4iot",
        },                                        
    ],
    instances: [
        {
            label: "image",
            declaration: "const image = go.Image()",
            insert: "image = go.Image();",
            info: "Create Image instance",
        },
    ],
};
