import { applyFunction, ClassDef } from "../tools";

export const imageGray16Class: ClassDef = {
    name: "image.Gray16",
    methods: [
        {
            label: "At",
            type: "method",
            info: "Returns the color value at the specified coordinates.",
            detail: "(x, y int) => color.Color",
            apply: applyFunction("At(x, y)", 3, 4),
            returnType: "color.Color",
            source: "go_method",
        },
        {
            label: "Bounds()",
            type: "method",
            info: "Returns the bounds of the image.",
            detail: "() => image.Rectangle",
            apply: "Bounds()",
            returnType: "image.Rectangle",
            source: "go_method",
        },
        {
            label: "ColorModel",
            type: "method",
            info: "Returns the color model of the image.",
            detail: "() => color.Model",
            apply: "ColorModel()",
            returnType: "color.Model",
            source: "go_method",
        },
        {
            label: "Gray16At",
            type: "method",
            info: "Returns the gray value at the specified coordinates.",
            detail: "(x, y int) => color.Gray16",
            apply: applyFunction("Gray16At(x, y)", 9, 10),
            returnType: "color.Gray16",
            source: "go_method",
        },
        {
            label: "Opaque",
            type: "method",
            info: "Returns whether the image is opaque.",
            detail: "() => bool",
            apply: "Opaque()",
            returnType: "bool",
            source: "go_method",
        },
        {
            label: "PixOffset",
            type: "method",
            info: "Returns the pixel offset for the specified coordinates.",
            detail: "(x, y int) => int",
            apply: applyFunction("PixOffset(x, y)", 10, 11),
            returnType: "int",
            source: "go_method",
        },
        {
            label: "RGBA64At",
            type: "method",
            info: "Returns the RGBA64 color value at the specified coordinates.",
            detail: "(x, y int) => color.RGBA64",
            apply: applyFunction("RGBA64At(x, y)", 12, 13),
            returnType: "color.RGBA64",
            source: "go_method",
        },
        {
            label: "Set",
            type: "method",
            info: "Sets the color value at the specified coordinates.",
            detail: "(x, y int, c color.Color)",
            apply: applyFunction("Set(x, y, c)", 4, 5),
            returnType: "void",
            source: "go_method",
        },
        {
            label: "SetGray16",
            type: "method",
            info: "Sets the gray value at the specified coordinates.",
            detail: "(x, y int, c color.Gray16)",
            apply: applyFunction("SetGray16(x, y, c)", 10, 11),
            returnType: "void",
            source: "go_method",
        },
        {
            label: "SetRGBA64",
            type: "method",
            info: "Sets the RGBA64 value at the specified coordinates.",
            detail: "(x, y int, c color.RGBA64)",
            apply: applyFunction("SetRGBA64(x, y, c)", 10, 11),
            returnType: "void",
            source: "go_method",
        },
        {
            label: "SubImage",
            type: "method",
            info: "Returns a sub-image defined by the specified rectangle.",
            detail: "(r Rectangle) => image.Image",
            apply: applyFunction("SubImage(r)", 9, 10),
            returnType: "Image",
            source: "go_method",
        },
    ],
    instances: [],
};