import { applyFunction, ClassDef } from "../tools";

export const dspClass: ClassDef = {
    name: "dsp.DSP",
    methods: [
        {
            label: "DetrendInPlace",
            type: "method",
            info: "Removes linear trend from x (in place). Uses least squares to estimate slope and intercept.",
            detail: "() => float64",
            apply: applyFunction("DetrendInPlace(x)", 15, 16),
            returnType: "float64",
            source: "osi4iot",
        },
        {
            label: "EstimateUniformSamplingRate",
            type: "method",
            info: "Returns the estimated uniform sampling rate.",
            detail: "(times []float64, method string) => float64",
            apply: applyFunction("EstimateUniformSamplingRate(times, method)", 28, 33),
            returnType: "float64",
            source: "osi4iot",
        },
        {
            label: "FindWelchPeaks",
            type: "method",
            info: "Returns the detected peaks in the Welch PSD.",
            detail: "(freq, psd []float64, df float64, cfg WelchConfig) => []Peak",
            apply: applyFunction("FindWelchPeaks(freq, psd, df, cfg)", 15, 16),
            returnType: "[]dsp.Peak",
            source: "osi4iot",
        },
        {
            label: "GetDefaultWelchConfig",
            type: "method",
            info: "Creates a dsp.WelchConfig variable with default parameters based on the sampling rate fs.",
            detail: "(fs float64) => dsp.WelchConfig",
            apply: applyFunction("GetDefaultWelchConfig(fs)", 22, 24),
            returnType: "dsp.WelchConfig",
            source: "osi4iot",
        },
        {
            label: "GetInterpolationConfig",
            type: "method",
            info: "Returns an InterpolationConfig with the specified parameters.",
            detail: "(targetFs float64, startTime float64, endTime float64, extrapolMode string) => dsp.InterpolationConfig",
            apply: applyFunction("GetInterpolationConfig(targetFs, startTime, endTime, extrapolMode)", 23, 31),
            returnType: "dsp.InterpolationConfig",
            source: "osi4iot",
        },
        {
            label: "GetWelchConfig",
            type: "method",
            info: "Returns a WelchConfig with the specified parameters.",
            detail: "(fs float64, winLen int, overlap float64, nfft int, zeroPadToNFFT bool, minFreq float64, maxFreq float64, minProminenceDB float64, minDistanceHz float64, smoothBins int) => dsp.WelchConfig",
            apply: applyFunction("GetWelchConfig(fs, winLen, overlap, nfft, zeroPadToNFFT, minFreq, maxFreq, minProminenceDB, minDistanceHz, smoothBins)", 15, 17),
            returnType: "dsp.WelchConfig",
            source: "osi4iot",
        },
        {
            label: "InterpolateToUniform",
            type: "method",
            info: "Interpolates the given time series data to a uniform grid.",
            detail: "(times []float64, values []float64, config InterpolationConfig) => []float64",
            apply: applyFunction("InterpolateToUniform(times, values, config)", 21, 26),
            returnType: "[]float64",
            source: "osi4iot",
        },
        {
            label: "SortTimeSeriesData",
            type: "method",
            info: "Sorts the TimeSeriesData by the 'times' field, maintaining the correspondence with 'values'.",
            detail: "(times []float64, values []float64) => ([]float64, []float64)",
            apply: applyFunction("SortTimeSeriesData(times, values)", 19, 24),
            returnType: "[[]float64, []float64]",
            source: "osi4iot",
        },
        {
            label: "WelchPSD",
            type: "method",
            info: "Computes the Power Spectral Density (PSD) using Welch's method.",
            detail: "(x []float64, cfg WelchConfig) => (freq []float64, psd []float64, df float64)",
            apply: applyFunction("WelchPSD(x, cfg)", 9, 10),
            returnType: "[req []float64, psd []float64, df float64]",
            source: "osi4iot",
        },
    ],
    instances: [
        {
            label: "dsp",
            declaration: "const dsp = go.DSP()",
            insert: "dsp = go.DSP();",
            info: "Create DSP instance",
        },        
    ],
};
