import { applyFunction, ClassDef } from "../tools";

export const colorClass: ClassDef = {
    name: "color.Color",
    methods: [
        {
            label: "Black",
            type: "constant",
            info: "",
            detail: "Color constant representing black.",
            apply: "Black",
            returnType: "color.Color",
            source: "go_constant",
        }, 
        {
            label: "White",
            type: "constant",
            info: "",
            detail: "Color constant representing white.",
            apply: "White",
            returnType: "color.Color",
            source: "go_constant",
        },
        {
            label: "Transparent",
            type: "constant",
            info: "",
            detail: "Color constant representing transparent.",
            apply: "Transparent",
            returnType: "color.Color",
            source: "go_constant",
        },
        {
            label: "Opaque",
            type: "constant",
            info: "",
            detail: "Color constant representing opaque",
            apply: "Opaque",
            returnType: "color.Color",
            source: "go_constant",
        },                               
        {
            label: "NewAlpha",
            type: "method",
            info: "Create a new Alpha color.",
            detail: "(a uint8) => color.Alpha",
            apply: applyFunction('NewAlpha(a)', 9, 10),
            returnType: "color.Alpha",
            source: "osi4iot",
        },
        {
            label: "NewAlpha16",
            type: "method",
            info: "Create a new Alpha16 color.",
            detail: "(a uint16) => color.Alpha16",
            apply: applyFunction('NewAlpha16(a)', 11, 12),
            returnType: "color.Alpha16",
            source: "osi4iot",
        },
        {
            label: "NewCMYK",
            type: "method",
            info: "Create a new CMYK color.",
            detail: "(c, m, y, k uint8) => color.CMYK",
            apply: applyFunction('NewCMYK(c, m, y, k)', 8, 9),
            returnType: "color.CMYK",
            source: "osi4iot",
        },
        {
            label: "NewGray",
            type: "method",
            info: "Create a new Gray color.",
            detail: "(g uint8) => color.Gray",
            apply: applyFunction('NewGray(g)', 8, 9),
            returnType: "color.Gray",
            source: "osi4iot",
        },
        {
            label: "NewGray16",
            type: "method",
            info: "Create a new Gray16 color.",
            detail: "(g uint16) => color.Gray16",
            apply: applyFunction('NewGray16(g)', 10, 11),
            returnType: "color.Gray16",
            source: "osi4iot",
        },
        {
            label: "NewNRGBA",
            type: "method",
            info: "Create a new NRGBA color.",
            detail: "(r, g, b, a uint8) => color.NRGBA",
            apply: applyFunction('NewNRGBA(r, g, b, a)', 9, 10),
            returnType: "color.NRGBA",
            source: "osi4iot",
        },
        {
            label: "NewNRGBA64",
            type: "method",
            info: "Create a new NRGBA64 color.",
            detail: "(r, g, b, a uint16) => color.NRGBA64",
            apply: applyFunction('NewNRGBA64(r, g, b, a)', 11, 12),
            returnType: "color.NRGBA64",
            source: "osi4iot",
        },
        {
            label: "NewNYCbCrA",
            type: "method",
            info: "Create a new NYCbCrA color.",
            detail: "(y, cb, cr, a uint8) => color.NYCbCrA",
            apply: applyFunction('NewNYCbCrA(y, cb, cr, a)', 11, 12),
            returnType: "color.NYCbCrA",
            source: "osi4iot",
        },
        {
            label: "NewPalette",
            type: "method",
            info: "Create a new color.Palette.",
            detail: "(colors []color.Color) => color.Palette",
            apply: applyFunction('NewPalette(colors)', 11, 17),
            returnType: "color.Palette",
            source: "osi4iot",
        },
        {
            label: "NewRGBA",
            type: "method",
            info: "Create a new RGBA color.",
            detail: "(r, g, b, a uint8) => color.RGBA",
            apply: applyFunction('NewRGBA(r, g, b, a)', 8, 9),
            returnType: "color.RGBA",
            source: "osi4iot",
        },
        {
            label: "NewRGBA64",
            type: "method",
            info: "Create a new RGBA64 color.",
            detail: "(r, g, b, a uint16) => color.RGBA64",
            apply: applyFunction('NewRGBA64(r, g, b, a)', 10, 11),
            returnType: "color.RGBA64",
            source: "osi4iot",
        },
        {
            label: "NewYCbCr",
            type: "method",
            info: "Create a new YCbCr color.",
            detail: "(y, cb, cr uint8) => color.YCbCr",
            apply: applyFunction('NewYCbCr(y, cb, cr)', 9, 10),
            returnType: "color.YCbCr",
            source: "osi4iot",
        },
        {
            label: "CMYKToRGB",
            type: "method",
            info: "Convert CMYK color to RGB.",
            detail: "(c, m, y, k uint8) => (uint8, uint8, uint8)",
            apply: applyFunction('CMYKToRGB(c, m, y, k)', 10, 11),
            returnType: "[uint8, uint8, uint8]",
            source: "go_function",
        },
        {
            label: "ModelFunc",
            type: "method",
            info: "Returns a Model that invokes f to implement the conversion.",
            detail: "(f func(color.Color) color.Color) => color.Model",
            apply: applyFunction('ModelFunc(f)', 10, 11),
            returnType: "color.Model",
            source: "go_function",
        },
        {
            label: "RGBToCMYK",
            type: "method",
            info: "Convert RGB color to CMYK.",
            detail: "(r, g, b uint8) => (uint8, uint8, uint8, uint8)",
            apply: applyFunction('RGBToCMYK(r, g, b)', 10, 11),
            returnType: "[uint8, uint8, uint8, uint8]",
            source: "go_function",
        },
        {
            label: "RGBToYCbCr",
            type: "method",
            info: "Convert RGB color to YCbCr.",
            detail: "(r, g, b uint8) => (uint8, uint8, uint8)",
            apply: applyFunction('RGBToYCbCr(r, g, b)', 11, 12),
            returnType: "[uint8, uint8, uint8]",
            source: "go_function",
        }, 
        {
            label: "YCbCrToRGB",
            type: "method",
            info: "Convert YCbCr color to RGB.",
            detail: "(y, cb, cr uint8) => (uint8, uint8, uint8)",
            apply: applyFunction('YCbCrToRGB(y, cb, cr)', 11, 12),
            returnType: "[uint8, uint8, uint8]",
            source: "go_function",
        },                                                                                   
    ],
    instances: [
        {
            label: "color",
            declaration: "const color = go.Color()",
            insert: "color = go.Color();",
            info: "Create Color instance",
        },
    ],
};
