package initPlatform

import (
	"log"
	"time"

	tea "github.com/charmbracelet/bubbletea"
	"github.com/osi4iot/osi4iot/utils/osi4iot_go_cli/ui/form"
	clipboard "github.com/tiagomelo/go-clipboard/clipboard"
)

func Create() {
	p := tea.NewProgram(initialModel())

	if _, err := p.Run(); err != nil {
		log.Fatal(err)
	}
}

func initialModel() form.Model {
	newClipboard := clipboard.New()
	model := form.Model{
		Questions: []form.Question{
			{
				Key:            "PLATFORM_NAME",
				QuestionType:   "generic",
				Prompt:         "Platform name",
				Answer:         "",
				DefaultAnswer:  "OSI-DEMO",
				ErrorMessage:   "",
				Choices:        []string{},
				ChoiceFocus:    0,
				Rules:          []string{"required", "isString", "minlen:4", "maxlen:15"},
				ActionRequired: false,
				Margin:         0,
			},
			{
				Key:            "DOMAIN_NAME",
				QuestionType:   "generic",
				Prompt:         "Domain name",
				Answer:         "",
				DefaultAnswer:  "",
				ErrorMessage:   "",
				Choices:        []string{},
				ChoiceFocus:    0,
				Rules:          []string{"required", "isString"},
				ActionRequired: false,
				Margin:         0,
			},
			{
				Key:            "PLATFORM_PHRASE",
				QuestionType:   "generic",
				Prompt:         "Platform motivational phrase",
				Answer:         "",
				DefaultAnswer:  "Open source integration for internet of things",
				ErrorMessage:   "",
				Choices:        []string{},
				ChoiceFocus:    0,
				Rules:          []string{"required", "isString"},
				ActionRequired: false,
				Margin:         0,
			},
			{
				Key:            "PLATFORM_ADMIN_FIRST_NAME",
				QuestionType:   "generic",
				Prompt:         "Platform admin first name",
				Answer:         "",
				DefaultAnswer:  "",
				ErrorMessage:   "",
				Choices:        []string{},
				ChoiceFocus:    0,
				Rules:          []string{"required", "isString", "minlen:2", "maxlen:20"},
				ActionRequired: false,
				Margin:         0,
			},
			{
				Key:            "PLATFORM_ADMIN_SURNAME",
				QuestionType:   "generic",
				Prompt:         "Platform admin last name",
				Answer:         "",
				DefaultAnswer:  "",
				ErrorMessage:   "",
				Choices:        []string{},
				ChoiceFocus:    0,
				Rules:          []string{"required", "isString", "minlen:2", "maxlen:20"},
				ActionRequired: false,
				Margin:         0,
			},
			{
				Key:            "PLATFORM_ADMIN_USER_NAME",
				QuestionType:   "generic",
				Prompt:         "Platform admin user name",
				Answer:         "",
				DefaultAnswer:  "",
				ErrorMessage:   "",
				Choices:        []string{},
				ChoiceFocus:    0,
				Rules:          []string{"required", "isString", "minlen:6", "maxlen:20"},
				ActionRequired: false,
				Margin:         0,
			},
			{
				Key:            "PLATFORM_ADMIN_EMAIL",
				QuestionType:   "generic",
				Prompt:         "Platform admin email",
				Answer:         "",
				ErrorMessage:   "",
				Choices:        []string{},
				ChoiceFocus:    0,
				Rules:          []string{"required", "email"},
				ActionRequired: false,
				Margin:         0,
			},
			{
				Key:            "PLATFORM_ADMIN_PASSWORD_INI",
				QuestionType:   "password",
				Prompt:         "Platform admin password",
				Answer:         "",
				DefaultAnswer:  "",
				ErrorMessage:   "",
				Choices:        []string{},
				ChoiceFocus:    0,
				Rules:          []string{"required", "string", "password"},
				ActionRequired: false,
				Margin:         0,
			},
			{
				Key:            "PLATFORM_ADMIN_PASSWORD",
				QuestionType:   "password",
				Prompt:         "Retype platform admin password",
				Answer:         "",
				DefaultAnswer:  "",
				ErrorMessage:   "",
				Choices:        []string{},
				ChoiceFocus:    0,
				Rules:          []string{"required", "string", "password", "matchPrevious"},
				ActionRequired: false,
				Margin:         0,
			},
			{
				Key:            "MIN_LONGITUDE",
				QuestionType:   "generic",
				Prompt:         "Min longitude of the geographical zone of the platform",
				Answer:         "",
				DefaultAnswer:  "-10.56884765625",
				ErrorMessage:   "",
				Choices:        []string{},
				ChoiceFocus:    0,
				Rules:          []string{"required", "float", "minval:-180", "maxval:180"},
				ActionRequired: false,
				Margin:         0,
			},
			{
				Key:            "MAX_LONGITUDE",
				QuestionType:   "generic",
				Prompt:         "Max longitude of the geographical zone of the platform",
				Answer:         "",
				DefaultAnswer:  "1.42822265625",
				ErrorMessage:   "",
				Choices:        []string{},
				ChoiceFocus:    0,
				Rules:          []string{"required", "float", "minval:-180", "maxval:180"},
				ActionRequired: false,
				Margin:         0,
			},
			{
				Key:            "MIN_LATITUDE",
				QuestionType:   "generic",
				Prompt:         "Min latitude of the geographical zone of the platform",
				Answer:         "",
				DefaultAnswer:  "35.55010533588552",
				ErrorMessage:   "",
				Choices:        []string{},
				ChoiceFocus:    0,
				Rules:          []string{"required", "float", "minval:-90", "maxval:90"},
				ActionRequired: false,
				Margin:         0,
			},
			{
				Key:            "MAX_LATITUDE",
				QuestionType:   "generic",
				Prompt:         "Max latitude of the geographical zone of the platform",
				Answer:         "",
				DefaultAnswer:  "44.134913443750726",
				ErrorMessage:   "",
				Choices:        []string{},
				ChoiceFocus:    0,
				Rules:          []string{"required", "float", "minval:-90", "maxval:90"},
				ActionRequired: false,
				Margin:         0,
			},
			{
				Key:            "DEFAULT_TIME_ZONE",
				QuestionType:   "generic",
				Prompt:         "Default time zone",
				Answer:         "",
				DefaultAnswer:  "Europe/Madrid",
				ErrorMessage:   "",
				Choices:        []string{},
				ChoiceFocus:    0,
				Rules:          []string{"required", "isString", "timeZone"},
				ActionRequired: false,
				Margin:         0,
			},
			{
				Key:            "MAIN_ORGANIZATION_NAME",
				QuestionType:   "generic",
				Prompt:         "Main organization name",
				Answer:         "",
				DefaultAnswer:  "",
				ErrorMessage:   "",
				Choices:        []string{},
				ChoiceFocus:    0,
				Rules:          []string{"required", "isString", "minlen:4", "maxlen:20"},
				ActionRequired: false,
				Margin:         0,
			},
			{
				Key:            "MAIN_ORGANIZATION_ACRONYM",
				QuestionType:   "generic",
				Prompt:         "Main organization acronym",
				Answer:         "",
				DefaultAnswer:  "",
				ErrorMessage:   "",
				Choices:        []string{},
				ChoiceFocus:    0,
				Rules:          []string{"required", "isString", "minlen:3", "maxlen:11"},
				ActionRequired: false,
				Margin:         0,
			},
			{
				Key:            "MAIN_ORGANIZATION_ADDRESS1",
				QuestionType:   "generic",
				Prompt:         "Main organization address",
				Answer:         "",
				DefaultAnswer:  "",
				ErrorMessage:   "",
				Choices:        []string{},
				ChoiceFocus:    0,
				Rules:          []string{"required", "isString", "minlen:4", "maxlen:50"},
				ActionRequired: false,
				Margin:         0,
			},
			{
				Key:            "MAIN_ORGANIZATION_CITY",
				QuestionType:   "generic",
				Prompt:         "Main organization city",
				Answer:         "",
				DefaultAnswer:  "",
				ErrorMessage:   "",
				Choices:        []string{},
				ChoiceFocus:    0,
				Rules:          []string{"required", "isString", "minlen:4", "maxlen:50"},
				ActionRequired: false,
				Margin:         0,
			},
			{
				Key:            "MAIN_ORGANIZATION_ZIP_CODE",
				QuestionType:   "generic",
				Prompt:         "Main organization zip code",
				Answer:         "",
				DefaultAnswer:  "",
				ErrorMessage:   "",
				Choices:        []string{},
				ChoiceFocus:    0,
				Rules:          []string{"required", "isString", "minlen:5", "maxlen:50"},
				ActionRequired: false,
				Margin:         0,
			},
			{
				Key:            "MAIN_ORGANIZATION_STATE",
				QuestionType:   "generic",
				Prompt:         "Main organization state/province",
				Answer:         "",
				DefaultAnswer:  "",
				ErrorMessage:   "",
				Choices:        []string{},
				ChoiceFocus:    0,
				Rules:          []string{"required", "isString", "minlen:4", "maxlen:50"},
				ActionRequired: false,
				Margin:         0,
			},
			{
				Key:            "MAIN_ORGANIZATION_COUNTRY",
				QuestionType:   "generic",
				Prompt:         "Main organization country",
				Answer:         "",
				DefaultAnswer:  "",
				ErrorMessage:   "",
				Choices:        []string{},
				ChoiceFocus:    0,
				Rules:          []string{"required", "country"},
				ActionRequired: false,
				Margin:         0,
			},
			{
				Key:            "MAIN_ORGANIZATION_BUILDING_PATH",
				QuestionType:   "generic",
				Prompt:         "Main organization building path",
				Answer:         "",
				DefaultAnswer:  "",
				ErrorMessage:   "",
				Choices:        []string{},
				ChoiceFocus:    0,
				Rules:          []string{"required", "string", "fileExists"},
				ActionRequired: false,
				Margin:         0,
			},
			{
				Key:            "MAIN_ORGANIZATION_FLOOR_PATH",
				QuestionType:   "generic",
				Prompt:         "Main organization floor path",
				Answer:         "",
				DefaultAnswer:  "",
				ErrorMessage:   "",
				Choices:        []string{},
				ChoiceFocus:    0,
				Rules:          []string{"required", "string"},
				ActionRequired: false,
				Margin:         0,
			},
			{
				Key:            "TELEGRAM_BOTTOKEN",
				QuestionType:   "generic",
				Prompt:         "Telegram boottoken for main organization default group",
				Answer:         "",
				DefaultAnswer:  "",
				ErrorMessage:   "",
				Choices:        []string{},
				ChoiceFocus:    0,
				Rules:          []string{"required", "string", "minlen:20"},
				ActionRequired: false,
				Margin:         0,
			},
			{
				Key:            "MAIN_ORGANIZATION_TELEGRAM_CHAT_ID",
				QuestionType:   "generic",
				Prompt:         "Telegram chat id for main organization default group",
				Answer:         "",
				DefaultAnswer:  "",
				ErrorMessage:   "",
				Choices:        []string{},
				ChoiceFocus:    0,
				Rules:          []string{"required", "int"},
				ActionRequired: false,
				Margin:         0,
			},
			{
				Key:            "MAIN_ORGANIZATION_TELEGRAM_INVITATION_LINK",
				QuestionType:   "generic",
				Prompt:         "Telegram invitation link for main organization default group",
				Answer:         "",
				DefaultAnswer:  "",
				ErrorMessage:   "",
				Choices:        []string{},
				ChoiceFocus:    0,
				Rules:          []string{"required", "url"},
				ActionRequired: false,
				Margin:         0,
			},
			{
				Key:            "NUMBER_OF_NODERED_INSTANCES_IN_MAIN_ORG",
				QuestionType:   "generic",
				Prompt:         "Number of node-red instances in main org",
				Answer:         "",
				DefaultAnswer:  "1",
				ErrorMessage:   "",
				Choices:        []string{},
				ChoiceFocus:    0,
				Rules:          []string{"required", "int", "minval:1", "maxval:10"},
				ActionRequired: false,
				Margin:         0,
			},
			{
				Key:            "NOTIFICATIONS_EMAIL_ADDRESS",
				QuestionType:   "generic",
				Prompt:         "Email account for platform notifications",
				Answer:         "",
				DefaultAnswer:  "",
				ErrorMessage:   "",
				Choices:        []string{},
				ChoiceFocus:    0,
				Rules:          []string{"required", "email"},
				ActionRequired: false,
				Margin:         0,
			},
			{
				Key:            "NOTIFICATIONS_EMAIL_PASSWORD",
				QuestionType:   "generic",
				Prompt:         "Email account password",
				Answer:         "",
				DefaultAnswer:  "",
				ErrorMessage:   "",
				Choices:        []string{},
				ChoiceFocus:    0,
				Rules:          []string{"required", "string", "password"},
				ActionRequired: false,
				Margin:         0,
			},
			{
				Key:            "REGISTRATION_TOKEN_LIFETIME",
				QuestionType:   "generic",
				Prompt:         "Registration token lifetime in seconds",
				Answer:         "",
				DefaultAnswer:  "86400",
				ErrorMessage:   "",
				Choices:        []string{},
				ChoiceFocus:    0,
				Rules:          []string{"required", "int", "minval:3600"},
				ActionRequired: false,
				Margin:         0,
			},
			{
				Key:            "ACCESS_TOKEN_LIFETIME",
				QuestionType:   "generic",
				Prompt:         "Access token lifetime in seconds",
				Answer:         "",
				DefaultAnswer:  "604800",
				ErrorMessage:   "",
				Choices:        []string{},
				ChoiceFocus:    0,
				Rules:          []string{"required", "int", "minval:3600"},
				ActionRequired: false,
				Margin:         0,
			},
			{
				Key:            "REFRESH_TOKEN_LIFETIME",
				QuestionType:   "generic",
				Prompt:         "Refresh token lifetime in seconds",
				Answer:         "",
				DefaultAnswer:  "31536000",
				ErrorMessage:   "",
				Choices:        []string{},
				ChoiceFocus:    0,
				Rules:          []string{"required", "int", "minval:86400"},
				ActionRequired: false,
				Margin:         0,
			},
			{
				Key:            "MQTT_SSL_CERTS_VALIDITY_DAYS",
				QuestionType:   "generic",
				Prompt:         "Mqtt ssl certs validity days",
				Answer:         "",
				DefaultAnswer:  "365",
				ErrorMessage:   "",
				Choices:        []string{},
				ChoiceFocus:    0,
				Rules:          []string{"required", "int", "minval:30"},
				ActionRequired: false,
				Margin:         0,
			},
			{
				Key:            "TIMESCALE_DATA_RET_INT_DAYS",
				QuestionType:   "generic",
				Prompt:         "Data retention interval in days for timescaldb",
				Answer:         "",
				DefaultAnswer:  "7",
				ErrorMessage:   "",
				Choices:        []string{},
				ChoiceFocus:    0,
				Rules:          []string{"required", "int", "minval:1"},
				ActionRequired: false,
				Margin:         0,
			},
			{
				Key:            "DEPLOYMENT_LOCATION",
				QuestionType:   "list",
				Prompt:         "Select the place of deployment of the platform",
				Answer:         "",
				DefaultAnswer:  "",
				ErrorMessage:   "",
				Choices:        []string{"Local deployment", "On-premise cluster deployment", "AWS cluster deployment"},
				ChoiceFocus:    0,
				Rules:          []string{"required"},
				ActionRequired: false,
				Margin:         0,
			},
			{
				Key:            "S3_BUCKET_TYPE",
				QuestionType:   "list",
				Prompt:         "Choose the type of S3 bucket to be used",
				Answer:         "",
				DefaultAnswer:  "",
				ErrorMessage:   "",
				Choices:        []string{"Local Minio", "Cloud AWS S3"},
				ChoiceFocus:    0,
				Rules:          []string{"required"},
				ActionRequired: false,
				Margin:         0,
			},
			{
				Key:            "S3_BUCKET_NAME",
				QuestionType:   "generic",
				Prompt:         "S3 storage bucket name",
				Answer:         "",
				DefaultAnswer:  "",
				ErrorMessage:   "",
				Choices:        []string{},
				ChoiceFocus:    0,
				Rules:          []string{"required", "string", "s3BucketName"},
				ActionRequired: false,
				Margin:         0,
			},
			{
				Key:            "NUMBER_OF_SWARM_NODES",
				QuestionType:   "generic",
				Prompt:         "Number of nodes in the platform",
				Answer:         "",
				DefaultAnswer:  "",
				ErrorMessage:   "",
				Choices:        []string{},
				ChoiceFocus:    0,
				Rules:          []string{"required", "isInt", "minval:1", "maxval:100"},
				ActionRequired: true,
				Margin:         0,
			},
			{
				Key:            "telephone",
				QuestionType:   "generic",
				Prompt:         "Telefon?",
				Answer:         "",
				DefaultAnswer:  "",
				ErrorMessage:   "",
				Choices:        []string{},
				ChoiceFocus:    0,
				Rules:          []string{"required", "isInt"},
				ActionRequired: true,
				Margin:         0,
			},
		},
		Focus:   0,
		Cursor:  0,
		Loading: false,
		SubmitMsgMap: map[string]string{
			"telephone":       "Sending telephone number",
			"NUMBER_OF_SWARM_NODES": "Adding node/s to swarm",
		},
		RecievedMsg:   "",
		PageSize:      10,
		CurrentPage:   1,
		TickInterval:  500 * time.Millisecond,
		CursorVisible: true,
		Clipboard:     newClipboard,
		Data:          map[string]interface{}{"numNodes": 0},
	}

	return model
}
