package form

import (
	"log"
	"strconv"
	"strings"
	"time"

	tea "github.com/charmbracelet/bubbletea"
	"github.com/osi4iot/osi4iot/utils/osi4iot_go_cli/internals/data"
	"github.com/osi4iot/osi4iot/utils/osi4iot_go_cli/internals/utils"
	clipboard "github.com/tiagomelo/go-clipboard/clipboard"
)

func CreatePlatform() {
	p := tea.NewProgram(initialModelCreatePlatform())

	if _, err := p.Run(); err != nil {
		log.Fatal(err)
	}
}

func initialModelCreatePlatform() Model {
	newClipboard := clipboard.New()
	model := Model{
		Questions: []Question{
			{
				Key:           "PLATFORM_NAME",
				QuestionType:  "generic",
				Prompt:        "Platform name",
				Answer:        data.Data.PlatformInfo.PlatformName,
				DefaultAnswer: "OSI-DEMO",
				ErrorMessage:  "",
				Choices:       []string{},
				ChoiceFocus:   0,
				Rules:         []string{"required", "isString", "platformName"},
				ActionKey:     "",
				Margin:        0,
			},
			{
				Key:           "DOMAIN_NAME",
				QuestionType:  "generic",
				Prompt:        "Domain name",
				Answer:        data.Data.PlatformInfo.DomainName,
				DefaultAnswer: "",
				ErrorMessage:  "",
				Choices:       []string{},
				ChoiceFocus:   0,
				Rules:         []string{"required", "isString"},
				ActionKey:     "",
				Margin:        0,
			},
			{
				Key:           "PLATFORM_PHRASE",
				QuestionType:  "generic",
				Prompt:        "Platform motivational phrase",
				Answer:        data.Data.PlatformInfo.PlatformPhrase,
				DefaultAnswer: "Open source integration for internet of things",
				ErrorMessage:  "",
				Choices:       []string{},
				ChoiceFocus:   0,
				Rules:         []string{"required", "isString"},
				ActionKey:     "",
				Margin:        0,
			},
			{
				Key:           "PLATFORM_ADMIN_FIRST_NAME",
				QuestionType:  "generic",
				Prompt:        "Platform admin first name",
				Answer:        data.Data.PlatformInfo.PlatformAdminFirstName,
				DefaultAnswer: "",
				ErrorMessage:  "",
				Choices:       []string{},
				ChoiceFocus:   0,
				Rules:         []string{"required", "isString", "minlen:2", "maxlen:20"},
				ActionKey:     "",
				Margin:        0,
			},
			{
				Key:           "PLATFORM_ADMIN_SURNAME",
				QuestionType:  "generic",
				Prompt:        "Platform admin last name",
				Answer:        data.Data.PlatformInfo.PlatformAdminSurname,
				DefaultAnswer: "",
				ErrorMessage:  "",
				Choices:       []string{},
				ChoiceFocus:   0,
				Rules:         []string{"required", "string", "minlen:2", "maxlen:20"},
				ActionKey:     "",
				Margin:        0,
			},
			{
				Key:           "PLATFORM_ADMIN_USER_NAME",
				QuestionType:  "generic",
				Prompt:        "Platform admin user name",
				Answer:        data.Data.PlatformInfo.PlatformAdminUserName,
				DefaultAnswer: "",
				ErrorMessage:  "",
				Choices:       []string{},
				ChoiceFocus:   0,
				Rules:         []string{"required", "string", "minlen:6", "maxlen:20"},
				ActionKey:     "",
				Margin:        0,
			},
			{
				Key:          "PLATFORM_ADMIN_EMAIL",
				QuestionType: "generic",
				Prompt:       "Platform admin email",
				Answer:       data.Data.PlatformInfo.PlatformAdminEmail,
				ErrorMessage: "",
				Choices:      []string{},
				ChoiceFocus:  0,
				Rules:        []string{"required", "email"},
				ActionKey:    "",
				Margin:       0,
			},
			{
				Key:           "PLATFORM_ADMIN_PASSWORD_INI",
				QuestionType:  "password",
				Prompt:        "Platform admin password",
				Answer:        data.Data.PlatformInfo.PlatformAdminPassword,
				DefaultAnswer: "",
				ErrorMessage:  "",
				Choices:       []string{},
				ChoiceFocus:   0,
				Rules:         []string{"required", "string", "password"},
				ActionKey:     "",
				Margin:        0,
			},
			{
				Key:           "PLATFORM_ADMIN_PASSWORD",
				QuestionType:  "password",
				Prompt:        "Retype platform admin password",
				Answer:        data.Data.PlatformInfo.PlatformAdminPassword,
				DefaultAnswer: "",
				ErrorMessage:  "",
				Choices:       []string{},
				ChoiceFocus:   0,
				Rules:         []string{"required", "string", "password", "matchPrevious"},
				ActionKey:     "",
				Margin:        0,
			},
			{
				Key:           "MIN_LONGITUDE",
				QuestionType:  "generic",
				Prompt:        "Min longitude of the geographical zone of the platform",
				Answer:        utils.FloatValueToStr(data.Data.PlatformInfo.MinLongitude),
				DefaultAnswer: "-10.56884765625",
				ErrorMessage:  "",
				Choices:       []string{},
				ChoiceFocus:   0,
				Rules:         []string{"required", "float", "minval:-180", "maxval:180"},
				ActionKey:     "",
				Margin:        0,
			},
			{
				Key:           "MAX_LONGITUDE",
				QuestionType:  "generic",
				Prompt:        "Max longitude of the geographical zone of the platform",
				Answer:        utils.FloatValueToStr(data.Data.PlatformInfo.MaxLongitude),
				DefaultAnswer: "1.42822265625",
				ErrorMessage:  "",
				Choices:       []string{},
				ChoiceFocus:   0,
				Rules:         []string{"required", "float", "minval:-180", "maxval:180"},
				ActionKey:     "",
				Margin:        0,
			},
			{
				Key:           "MIN_LATITUDE",
				QuestionType:  "generic",
				Prompt:        "Min latitude of the geographical zone of the platform",
				Answer:        utils.FloatValueToStr(data.Data.PlatformInfo.MinLatitude),
				DefaultAnswer: "35.55010533588552",
				ErrorMessage:  "",
				Choices:       []string{},
				ChoiceFocus:   0,
				Rules:         []string{"required", "float", "minval:-90", "maxval:90"},
				ActionKey:     "",
				Margin:        0,
			},
			{
				Key:           "MAX_LATITUDE",
				QuestionType:  "generic",
				Prompt:        "Max latitude of the geographical zone of the platform",
				Answer:        utils.FloatValueToStr(data.Data.PlatformInfo.MaxLatitude),
				DefaultAnswer: "44.134913443750726",
				ErrorMessage:  "",
				Choices:       []string{},
				ChoiceFocus:   0,
				Rules:         []string{"required", "float", "minval:-90", "maxval:90"},
				ActionKey:     "",
				Margin:        0,
			},
			{
				Key:           "DEFAULT_TIME_ZONE",
				QuestionType:  "generic",
				Prompt:        "Default time zone",
				Answer:        data.Data.PlatformInfo.DefaultTimeZone,
				DefaultAnswer: "Europe/Madrid",
				ErrorMessage:  "",
				Choices:       []string{},
				ChoiceFocus:   0,
				Rules:         []string{"required", "isString", "timeZone"},
				ActionKey:     "",
				Margin:        0,
			},
			{
				Key:           "MAIN_ORGANIZATION_NAME",
				QuestionType:  "generic",
				Prompt:        "Main organization name",
				Answer:        data.Data.PlatformInfo.MainOrganizationName,
				DefaultAnswer: "",
				ErrorMessage:  "",
				Choices:       []string{},
				ChoiceFocus:   0,
				Rules:         []string{"required", "isString", "minlen:4", "maxlen:40"},
				ActionKey:     "",
				Margin:        0,
			},
			{
				Key:           "MAIN_ORGANIZATION_ACRONYM",
				QuestionType:  "generic",
				Prompt:        "Main organization acronym",
				Answer:        data.Data.PlatformInfo.MainOrganizationAcronym,
				DefaultAnswer: "",
				ErrorMessage:  "",
				Choices:       []string{},
				ChoiceFocus:   0,
				Rules:         []string{"required", "isString", "minlen:3", "maxlen:11"},
				ActionKey:     "",
				Margin:        0,
			},
			{
				Key:           "MAIN_ORGANIZATION_ADDRESS1",
				QuestionType:  "generic",
				Prompt:        "Main organization address",
				Answer:        data.Data.PlatformInfo.MainOrganizationAddress1,
				DefaultAnswer: "",
				ErrorMessage:  "",
				Choices:       []string{},
				ChoiceFocus:   0,
				Rules:         []string{"required", "isString", "minlen:4", "maxlen:50"},
				ActionKey:     "",
				Margin:        0,
			},
			{
				Key:           "MAIN_ORGANIZATION_CITY",
				QuestionType:  "generic",
				Prompt:        "Main organization city",
				Answer:        data.Data.PlatformInfo.MainOrganizationCity,
				DefaultAnswer: "",
				ErrorMessage:  "",
				Choices:       []string{},
				ChoiceFocus:   0,
				Rules:         []string{"required", "isString", "minlen:4", "maxlen:50"},
				ActionKey:     "",
				Margin:        0,
			},
			{
				Key:           "MAIN_ORGANIZATION_ZIP_CODE",
				QuestionType:  "generic",
				Prompt:        "Main organization zip code",
				Answer:        data.Data.PlatformInfo.MainOrganizationZipCode,
				DefaultAnswer: "",
				ErrorMessage:  "",
				Choices:       []string{},
				ChoiceFocus:   0,
				Rules:         []string{"required", "isString", "minlen:5", "maxlen:50"},
				ActionKey:     "",
				Margin:        0,
			},
			{
				Key:           "MAIN_ORGANIZATION_STATE",
				QuestionType:  "generic",
				Prompt:        "Main organization state/province",
				Answer:        data.Data.PlatformInfo.MainOrganizationState,
				DefaultAnswer: "",
				ErrorMessage:  "",
				Choices:       []string{},
				ChoiceFocus:   0,
				Rules:         []string{"required", "isString", "minlen:4", "maxlen:50"},
				ActionKey:     "",
				Margin:        0,
			},
			{
				Key:           "MAIN_ORGANIZATION_COUNTRY",
				QuestionType:  "generic",
				Prompt:        "Main organization country",
				Answer:        data.Data.PlatformInfo.MainOrganizationCountry,
				DefaultAnswer: "",
				ErrorMessage:  "",
				Choices:       []string{},
				ChoiceFocus:   0,
				Rules:         []string{"required", "country"},
				ActionKey:     "",
				Margin:        0,
			},
			{
				Key:           "MAIN_ORGANIZATION_BUILDING_PATH",
				QuestionType:  "generic",
				Prompt:        "Main organization building path",
				Answer:        data.Data.PlatformInfo.MainOrganizationBuildingPath,
				DefaultAnswer: "./geojson/main_org_building.geojson",
				ErrorMessage:  "",
				Choices:       []string{},
				ChoiceFocus:   0,
				Rules:         []string{"required", "string", "fileOrFieldExists"},
				ActionKey:     "",
				Margin:        0,
			},
			{
				Key:           "MAIN_ORGANIZATION_FLOOR_PATH",
				QuestionType:  "generic",
				Prompt:        "Main organization floor path",
				Answer:        data.Data.PlatformInfo.MainOrganizationFirstFloorPath,
				DefaultAnswer: "./geojson/main_org_first_floor.geojson",
				ErrorMessage:  "",
				Choices:       []string{},
				ChoiceFocus:   0,
				Rules:         []string{"required", "string", "fileOrFieldExists"},
				ActionKey:     "",
				Margin:        0,
			},
			{
				Key:           "TELEGRAM_BOTTOKEN",
				QuestionType:  "generic",
				Prompt:        "Telegram boottoken for main organization default group",
				Answer:        data.Data.PlatformInfo.TelegramBotToken,
				DefaultAnswer: "",
				ErrorMessage:  "",
				Choices:       []string{},
				ChoiceFocus:   0,
				Rules:         []string{"required", "string", "minlen:20"},
				ActionKey:     "",
				Margin:        0,
			},
			{
				Key:           "MAIN_ORGANIZATION_TELEGRAM_CHAT_ID",
				QuestionType:  "generic",
				Prompt:        "Telegram chat id for main organization default group",
				Answer:        data.Data.PlatformInfo.MainOrganizationTelegramChatID,
				DefaultAnswer: "",
				ErrorMessage:  "",
				Choices:       []string{},
				ChoiceFocus:   0,
				Rules:         []string{"required", "int"},
				ActionKey:     "",
				Margin:        0,
			},
			{
				Key:           "MAIN_ORGANIZATION_TELEGRAM_INVITATION_LINK",
				QuestionType:  "generic",
				Prompt:        "Telegram invitation link for main organization default group",
				Answer:        data.Data.PlatformInfo.MainOrganizationTelegramInviteLink,
				DefaultAnswer: "",
				ErrorMessage:  "",
				Choices:       []string{},
				ChoiceFocus:   0,
				Rules:         []string{"required", "url"},
				ActionKey:     "",
				Margin:        0,
			},
			{
				Key:           "NOTIFICATIONS_EMAIL_ADDRESS",
				QuestionType:  "generic",
				Prompt:        "Email account for platform notifications",
				Answer:        data.Data.PlatformInfo.NotificationsEmailAddress,
				DefaultAnswer: "",
				ErrorMessage:  "",
				Choices:       []string{},
				ChoiceFocus:   0,
				Rules:         []string{"required", "email"},
				ActionKey:     "",
				Margin:        0,
			},
			{
				Key:           "NOTIFICATIONS_EMAIL_PASSWORD",
				QuestionType:  "password",
				Prompt:        "Email account password",
				Answer:        data.Data.PlatformInfo.NotificationsEmailPassword,
				DefaultAnswer: "",
				ErrorMessage:  "",
				Choices:       []string{},
				ChoiceFocus:   0,
				Rules:         []string{"required", "string", "password"},
				ActionKey:     "",
				Margin:        0,
			},
			{
				Key:           "REGISTRATION_TOKEN_LIFETIME",
				QuestionType:  "generic",
				Prompt:        "Registration token lifetime in seconds",
				Answer:        utils.IntValueToStr(data.Data.PlatformInfo.RegistrationTokenLifetime),
				DefaultAnswer: "86400",
				ErrorMessage:  "",
				Choices:       []string{},
				ChoiceFocus:   0,
				Rules:         []string{"required", "int", "minval:3600"},
				ActionKey:     "",
				Margin:        0,
			},
			{
				Key:           "ACCESS_TOKEN_LIFETIME",
				QuestionType:  "generic",
				Prompt:        "Access token lifetime in seconds",
				Answer:        utils.IntValueToStr(data.Data.PlatformInfo.AccessTokenLifetime),
				DefaultAnswer: "604800",
				ErrorMessage:  "",
				Choices:       []string{},
				ChoiceFocus:   0,
				Rules:         []string{"required", "int", "minval:3600"},
				ActionKey:     "",
				Margin:        0,
			},
			{
				Key:           "REFRESH_TOKEN_LIFETIME",
				QuestionType:  "generic",
				Prompt:        "Refresh token lifetime in seconds",
				Answer:        utils.IntValueToStr(data.Data.PlatformInfo.RefreshTokenLifetime),
				DefaultAnswer: "31536000",
				ErrorMessage:  "",
				Choices:       []string{},
				ChoiceFocus:   0,
				Rules:         []string{"required", "int", "minval:86400"},
				ActionKey:     "",
				Margin:        0,
			},
			{
				Key:           "NUM_NATS_CLUSTER_NODES",
				QuestionType:  "list",
				Prompt:        "Number of NATS cluster nodes",
				Answer:        utils.IntValueToStr(data.Data.PlatformInfo.NumNatsClusterNodes),
				DefaultAnswer: "1",
				ErrorMessage:  "",
				Choices:       []string{"1", "3", "5"},
				ChoiceFocus:   0,
				Rules:         []string{"required", "int", "minval:1"},
				ActionKey:     "",
				Margin:        0,
			},
			{
				Key:           "TIMESCALE_DATA_RET_INT_DAYS",
				QuestionType:  "generic",
				Prompt:        "Data retention interval in days for timescaldb",
				Answer:        strings.Split(data.Data.PlatformInfo.TimescaleDataRetentionInterval, " ")[0],
				DefaultAnswer: "7",
				ErrorMessage:  "",
				Choices:       []string{},
				ChoiceFocus:   0,
				Rules:         []string{"required", "int", "minval:1"},
				ActionKey:     "",
				Margin:        0,
			},
			{
				Key:           "NUMBER_DEV2PDB_WORKERS",
				QuestionType:  "generic",
				Prompt:        "Number of workers for store data in timescaldb",
				Answer:        utils.IntValueToStr(data.Data.PlatformInfo.NumberDev2pdbWorkers),
				DefaultAnswer: "10",
				ErrorMessage:  "",
				Choices:       []string{},
				ChoiceFocus:   0,
				Rules:         []string{"required", "int", "minval:1", "maxval:50"},
				ActionKey:     "",
				Margin:        0,
			},
			{
				Key:           "DEV2PDB_BATCH_SIZE",
				QuestionType:  "generic",
				Prompt:        "Batch size for store data in timescaldb",
				Answer:        utils.IntValueToStr(data.Data.PlatformInfo.Dev2pdbBatchSize),
				DefaultAnswer: "1000",
				ErrorMessage:  "",
				Choices:       []string{},
				ChoiceFocus:   0,
				Rules:         []string{"required", "int", "minval:1000", "maxval:50000"},
				ActionKey:     "",
				Margin:        0,
			},
			{
				Key:           "DEPLOYMENT_LOCATION",
				QuestionType:  "list",
				Prompt:        "Select the place of deployment of the platform",
				Answer:        data.Data.PlatformInfo.DeploymentLocation,
				DefaultAnswer: "",
				ErrorMessage:  "",
				Choices: []string{
					"Local deployment",
					"On-premise cluster deployment",
					"AWS cluster deployment",
				},
				ChoiceFocus: utils.GiveChoiceFocus(data.Data.PlatformInfo.DeploymentLocation,
					[]string{
						"Local deployment",
						"On-premise cluster deployment",
						"AWS cluster deployment",
					}, 0),
				Rules:     []string{"required"},
				ActionKey: "deploymentLocation",
				Margin:    0,
			},
			{
				Key:           "LOCAL_RESOURCE_UTILIZATION_PERCENTAGE",
				QuestionType:  "generic",
				Prompt:        "Local computer resource utilization percentage",
				Answer:        utils.IntValueToStr(data.Data.PlatformInfo.LocalResourceUtilization),
				DefaultAnswer: "100",
				ErrorMessage:  "",
				Choices:       []string{},
				ChoiceFocus:   0,
				Rules:         []string{"required", "int", "minval:50", "maxval:100"},
				ActionKey:     "",
				Margin:        0,
			},
			{
				Key:           "S3_BUCKET_TYPE",
				QuestionType:  "list",
				Prompt:        "Choose the type of S3 bucket to be used",
				Answer:        data.Data.PlatformInfo.S3BucketType,
				DefaultAnswer: "",
				ErrorMessage:  "",
				Choices:       []string{"Local Minio", "Cloud AWS S3"},
				ChoiceFocus: utils.GiveChoiceFocus(data.Data.PlatformInfo.S3BucketType,
					[]string{"Local Minio", "Cloud AWS S3"}, 0),
				Rules:     []string{"required"},
				ActionKey: "awsS3BucketQuestions",
				Margin:    0,
			},
			{
				Key:           "S3_BUCKET_NAME",
				QuestionType:  "generic",
				Prompt:        "S3 storage bucket name",
				Answer:        data.Data.PlatformInfo.S3BucketName,
				DefaultAnswer: "",
				ErrorMessage:  "",
				Choices:       []string{},
				ChoiceFocus:   0,
				Rules:         []string{"required", "string", "s3BucketName"},
				ActionKey:     "",
				Margin:        0,
			},
			{
				Key:           "DOMAIN_CERTS_TYPE",
				QuestionType:  "list",
				Prompt:        "Choose the type of domain ssl certs to be used",
				Answer:        data.Data.PlatformInfo.DomainCertsType,
				DefaultAnswer: "",
				ErrorMessage:  "",
				Choices: []string{
					"No certs",
					"Certs provided by an CA",
					"Let's encrypt certs with HTTP-01 challenge",
					"Let's encrypt certs with DNS-01 challenge and AWS Route 53 provider",
					"AWS Certificate Manager",
				},
				ChoiceFocus: utils.GiveChoiceFocus(data.Data.PlatformInfo.DomainCertsType,
					[]string{
						"No certs",
						"Certs provided by an CA",
						"Let's encrypt certs with HTTP-01 challenge",
						"Let's encrypt certs with DNS-01 challenge and AWS Route 53 provider",
						"AWS Certificate Manager",
					}, 0),
				Rules:     []string{"required", "domainCertsType"},
				ActionKey: "domainCertsQuestions",
				Margin:    0,
			},
			{
				Key:           "DEPLOYMENT_MODE",
				QuestionType:  "list",
				Prompt:        "Select deployment mode",
				Answer:        data.Data.PlatformInfo.DeploymentMode,
				DefaultAnswer: "",
				ErrorMessage:  "",
				Choices:       []string{"development", "production"},
				ChoiceFocus: utils.GiveChoiceFocus(data.Data.PlatformInfo.DeploymentMode,
					[]string{"development", "production"}, 0),
				Rules:     []string{"required"},
				ActionKey: "",
				Margin:    0,
			},
			{
				Key:           "MESSAGING_SVC_RESOURCES",
				QuestionType:  "list",
				Prompt:        "Select resources for messaging services (nats or mqtt)",
				Answer:        data.Data.PlatformInfo.MessagingSvcResources,
				DefaultAnswer: "",
				ErrorMessage:  "",
				Choices:       []string{"0.25CPU-500Mb", "0.5CPU-1000Mb", "1CPU-2000Mb", "2CPU-4000Mb", "3CPU-6000Mb", "4CPU-8000Mb"},
				ChoiceFocus: utils.GiveChoiceFocus(data.Data.PlatformInfo.MessagingSvcResources,
					[]string{"0.25CPU-500Mb", "0.5CPU-1000Mb", "1CPU-2000Mb", "2CPU-4000Mb", "3CPU-6000Mb", "4CPU-8000Mb"}, 0),
				Rules:     []string{"required"},
				ActionKey: "",
				Margin:    0,
			},
			{
				Key:           "IOT_DATA_STORAGE_SVC_RESOURCES",
				QuestionType:  "list",
				Prompt:        "Select resources for IoT data storage services",
				Answer:        data.Data.PlatformInfo.IotDataStorageSvcResources,
				DefaultAnswer: "",
				ErrorMessage:  "",
				Choices:       []string{"0.25CPU-500Mb", "0.5CPU-1000Mb", "1CPU-2000Mb", "2CPU-4000Mb", "3CPU-6000Mb", "4CPU-8000Mb"},
				ChoiceFocus: utils.GiveChoiceFocus(data.Data.PlatformInfo.IotDataStorageSvcResources,
					[]string{"0.25CPU-500Mb", "0.5CPU-1000Mb", "1CPU-2000Mb", "2CPU-4000Mb", "3CPU-6000Mb", "4CPU-8000Mb"}, 0),
				Rules:     []string{"required"},
				ActionKey: "",
				Margin:    0,
			},
			{
				Key:           "ADMIN_DATA_STORAGE_SVC_RESOURCES",
				QuestionType:  "list",
				Prompt:        "Select resources for admin data storage services",
				Answer:        data.Data.PlatformInfo.AdminDataStorageSvcResources,
				DefaultAnswer: "",
				ErrorMessage:  "",
				Choices:       []string{"0.25CPU-500Mb", "0.5CPU-1000Mb", "1CPU-2000Mb", "2CPU-4000Mb", "3CPU-6000Mb", "4CPU-8000Mb"},
				ChoiceFocus: utils.GiveChoiceFocus(data.Data.PlatformInfo.AdminDataStorageSvcResources,
					[]string{"0.25CPU-500Mb", "0.5CPU-1000Mb", "1CPU-2000Mb", "2CPU-4000Mb", "3CPU-6000Mb", "4CPU-8000Mb"}, 0),
				Rules:     []string{"required"},
				ActionKey: "",
				Margin:    0,
			},
			{
				Key:           "UI_SVC_RESOURCES",
				QuestionType:  "list",
				Prompt:        "Select resources for user interface services",
				Answer:        data.Data.PlatformInfo.UiSvcResources,
				DefaultAnswer: "",
				ErrorMessage:  "",
				Choices:       []string{"0.25CPU-500Mb", "0.5CPU-1000Mb", "1CPU-2000Mb", "2CPU-4000Mb"},
				ChoiceFocus: utils.GiveChoiceFocus(data.Data.PlatformInfo.UiSvcResources,
					[]string{"0.25CPU-500Mb", "0.5CPU-1000Mb", "1CPU-2000Mb", "2CPU-4000Mb"}, 0),
				Rules:     []string{"required"},
				ActionKey: "",
				Margin:    0,
			},
			{
				Key:           "PIPELINES_SVC_RESOURCES",
				QuestionType:  "list",
				Prompt:        "Select resources for pipelines services",
				Answer:        data.Data.PlatformInfo.PipelinesSvcResources,
				DefaultAnswer: "",
				ErrorMessage:  "",
				Choices:       []string{"0.25CPU-500Mb", "0.5CPU-1000Mb", "1CPU-2000Mb", "2CPU-4000Mb"},
				ChoiceFocus: utils.GiveChoiceFocus(data.Data.PlatformInfo.PipelinesSvcResources,
					[]string{"0.25CPU-500Mb", "0.5CPU-1000Mb", "1CPU-2000Mb", "2CPU-4000Mb"}, 0),
				Rules:     []string{"required"},
				ActionKey: "",
				Margin:    0,
			},		
			{
				Key:           "NUMBER_OF_PIPELINES_INSTANCES",
				QuestionType:  "list",
				Prompt:        "Number of pipelines instances",
				Answer:        utils.IntValueToStr(data.Data.PlatformInfo.NumPipelinesInstances),
				DefaultAnswer: "1",
				ErrorMessage:  "",
				Choices:       []string{"1", "3",  "5"},
				ChoiceFocus:   utils.GiveChoiceFocus(strconv.Itoa(data.Data.PlatformInfo.NumPipelinesInstances),
					[]string{"1", "3",  "5"}, 0),
				Rules:         []string{"required"},
				ActionKey:     "",
				Margin:        0,
			},
			{
				Key:           "confirmAnswers",
				QuestionType:  "generic",
				Prompt:        "Do you want to confirm the answers? (y/n)",
				Answer:        "",
				DefaultAnswer: "",
				ErrorMessage:  "",
				Choices:       []string{},
				ChoiceFocus:   0,
				Rules:         []string{"required", "string", "confirmAnswers"},
				ActionKey:     "createPlatform",
				Margin:        0,
			},
		},
		Focus:    0,
		Cursor:   0,
		Loading:  false,
		Finished: false,
		SubmitMsgMap: map[string]string{
			"createPlatform":           "Create platform",
			"creatingNodeQuestions":    "Adding node questions",
			"copyKeyInNode":            "Copying public key in node",
			"deploymentLocation":       "Setting questions for the deployment location selected",
		},
		RecievedMsg:   "",
		PageSize:      10,
		CurrentPage:   1,
		TickInterval:  500 * time.Millisecond,
		CursorVisible: true,
		Clipboard:     newClipboard,
		Data:          map[string]interface{}{"numNodes": 0},
	}

	model.Cursor = len(model.Questions[0].Answer)

	if data.Data.PlatformInfo.MainOrganizationBuilding == "" {
		if data.Data.PlatformInfo.MainOrganizationBuildingPath != "" {
			path := data.Data.PlatformInfo.MainOrganizationBuildingPath
			if utils.FileExists(path) {
				mainOrgBuilding := utils.GetFileData(path)
				data.Data.PlatformInfo.MainOrganizationBuilding = mainOrgBuilding
			}
		}
	}

	if data.Data.PlatformInfo.MainOrganizationFirstFloor == "" {
		if data.Data.PlatformInfo.MainOrganizationFirstFloorPath != "" {
			path := data.Data.PlatformInfo.MainOrganizationFirstFloorPath
			if utils.FileExists(path) {
				mainOrgFirstFloor := utils.GetFileData(path)
				data.Data.PlatformInfo.MainOrganizationFirstFloor = mainOrgFirstFloor
			}
		}
	}

	if data.Data.PlatformInfo.DomainCertsType == "Certs provided by an CA" {
		DomainCertsQuestions(&model)
	}

	if data.Data.PlatformInfo.DeploymentLocation != "Local deployment" {
		DeployLocationQuestions(&model)
	}

	return model
}
