import { applyFunction, ClassDef } from "../tools";

export const timeDurationClass: ClassDef = {
    name: "time.Duration",
    methods: [
        {
            label: "Abs",
            type: "method",
            info: "Returns the absolute value of d.",
            detail: "(d Duration) => time.Duration",
            apply: applyFunction("Abs(d)", 6, 8),
            returnType: "time.Duration",
            source: "go_method",
        },
        {
            label: "Hours",
            type: "method",
            info: "Returns the duration in hours.",
            detail: "() => float64",
            apply: "Hours()",
            returnType: "float64",
            source: "go_method",
        },
        {
            label: "Microseconds",
            type: "method",
            info: "Returns the duration in microseconds.",
            detail: "() => float64",
            apply: "Microseconds()",
            returnType: "float64",
            source: "go_method",
        },
        {
            label: "Milliseconds",
            type: "method",
            info: "Returns the duration in milliseconds.",
            detail: "() => float64",
            apply: "Milliseconds()",
            returnType: "float64",
            source: "go_method",
        },
        {
            label: "Minutes",
            type: "method",
            info: "Returns the duration in minutes.",
            detail: "() => float64",
            apply: "Minutes()",
            returnType: "float64",
            source: "go_method",
        },
        {
            label: "Nanoseconds",
            type: "method",
            info: "Returns the duration in nanoseconds.",
            detail: "() => float64",
            apply: "Nanoseconds()",
            returnType: "float64",
            source: "go_method",
        },
        {
            label: "Round",
            type: "method",
            info: "Rounds the duration to the nearest multiple of d.",
            detail: "(d Duration) => time.Duration",
            apply: applyFunction("Round(time.Minute)", 9, 20),
            returnType: "time.Duration",
            source: "go_method",
        },
        {
            label: "Seconds",
            type: "method",
            info: "Returns the duration in seconds.",
            detail: "() => float64",
            apply: "Seconds()",
            returnType: "float64",
            source: "go_method",
        },
        {
            label: "String",
            type: "method",
            info: "Returns the string representation of the duration.",
            detail: "() => string",
            apply: "String()",
            returnType: "string",
            source: "go_method",
        },
        {
            label: "Truncate",
            type: "method",
            info: "Return the result of rounding t down to a multiple of d (since the zero time). If d <= 0, Truncate returns t stripped of any monotonic clock reading but otherwise unchanged.",
            detail: "(d Duration) => time.Time",
            apply: applyFunction("Truncate(time.Minute)", 9, 20),
            returnType: "time.Time",
            source: "go_method",
        },
    ],
    instances: [],
};
