import { applyFunction, ClassDef } from "../tools";

export const timeClass: ClassDef = {
    name: "time.Time",
    methods: [
        {
            label: "ANSIC",
            type: "constant",
            info: "",
            detail: "ANSIC constant representing the ANSIC time format",
            apply: "ANSIC",
            returnType: "string",
            source: "go_constant",
        },
        {
            label: "April",
            type: "constant",
            info: "",
            detail: "April constant representing the April month",
            apply: "April",
            returnType: "time.Month",
            source: "go_constant",
        },
        {
            label: "August",
            type: "constant",
            info: "",
            detail: "August constant representing the August month",
            apply: "August",
            returnType: "time.Month",
            source: "go_constant",
        },
        {
            label: "DateOnly",
            type: "constant",
            info: "",
            detail: "DateOnly constant representing the DateOnly time format",
            apply: "DateOnly",
            returnType: "string",
            source: "go_constant",
        },
        {
            label: "DateTime",
            type: "constant",
            info: "",
            detail: "DateTime constant representing the DateTime time format",
            apply: "DateTime",
            returnType: "string",
            source: "go_constant",
        },
        {
            label: "December",
            type: "constant",
            info: "",
            detail: "December constant representing the December month",
            apply: "December",
            returnType: "time.Month",
            source: "go_constant",
        },
        {
            label: "February",
            type: "constant",
            info: "",
            detail: "February constant representing the February month",
            apply: "February",
            returnType: "time.Month",
            source: "go_constant",
        },
        {
            label: "Friday",
            type: "constant",
            info: "",
            detail: "Friday constant representing the Friday weekday",
            apply: "Friday",
            returnType: "Weekday",
            source: "go_constant",
        },
        {
            label: "Hour",
            type: "constant",
            info: "",
            detail: "Time constant representing one hour",
            apply: "Hour",
            returnType: "time.Duration",
            source: "go_constant",
        },
        {
            label: "January",
            type: "constant",
            info: "",
            detail: "January constant representing the January month",
            apply: "January",
            returnType: "time.Month",
            source: "go_constant",
        },
        {
            label: "July",
            type: "constant",
            info: "",
            detail: "July constant representing the July month",
            apply: "July",
            returnType: "time.Month",
            source: "go_constant",
        },
        {
            label: "June",
            type: "constant",
            info: "",
            detail: "June constant representing the June month",
            apply: "June",
            returnType: "time.Month",
            source: "go_constant",
        },
        {
            label: "Kitchen",
            type: "constant",
            info: "",
            detail: "Kitchen constant representing the Kitchen time format",
            apply: "Kitchen",
            returnType: "string",
            source: "go_constant",
        },
        {
            label: "Layout",
            type: "constant",
            info: "",
            detail: "Layout constant representing the default time format",
            apply: "Layout",
            returnType: "string",
            source: "go_constant",
        },
        {
            label: "Local",
            type: "constant",
            info: "",
            detail: "Time constant representing local location",
            apply: "Local",
            returnType: "time.Location",
            source: "go_constant",
        },
        {
            label: "March",
            type: "constant",
            info: "",
            detail: "March constant representing the March month",
            apply: "March",
            returnType: "time.Month",
            source: "go_constant",
        },
        {
            label: "May",
            type: "constant",
            info: "",
            detail: "May constant representing the May month",
            apply: "May",
            returnType: "time.Month",
            source: "go_constant",
        },
        {
            label: "Millisecond",
            type: "constant",
            info: "",
            detail: "Time constant representing one millisecond",
            apply: "Millisecond",
            returnType: "time.Duration",
            source: "go_constant",
        },
        {
            label: "Minute",
            type: "constant",
            info: "",
            detail: "Time constant representing one minute",
            apply: "Minute",
            returnType: "time.Duration",
            source: "go_constant",
        },
        {
            label: "Monday",
            type: "constant",
            info: "",
            detail: "Monday constant representing the Monday weekday",
            apply: "Monday",
            returnType: "Weekday",
            source: "go_constant",
        },
        {
            label: "Nanosecond",
            type: "constant",
            info: "",
            detail: "Time constant representing one nanosecond",
            apply: "Nanosecond",
            returnType: "time.Duration",
            source: "go_constant",
        },
        {
            label: "November",
            type: "constant",
            info: "",
            detail: "November constant representing the November month",
            apply: "November",
            returnType: "time.Month",
            source: "go_constant",
        },
        {
            label: "October",
            type: "constant",
            info: "",
            detail: "October constant representing the October month",
            apply: "October",
            returnType: "time.Month",
            source: "go_constant",
        },
        {
            label: "RFC1123",
            type: "constant",
            info: "",
            detail: "RFC1123 constant representing the RFC1123 time format",
            apply: "RFC1123",
            returnType: "string",
            source: "go_constant",
        },
        {
            label: "RFC1123Z",
            type: "constant",
            info: "",
            detail: "RFC1123Z constant representing the RFC1123Z time format",
            apply: "RFC1123Z",
            returnType: "string",
            source: "go_constant",
        },
        {
            label: "RFC3339",
            type: "constant",
            info: "",
            detail: "RFC3339 constant representing the RFC3339 time format",
            apply: "RFC3339",
            returnType: "string",
            source: "go_constant",
        },
        {
            label: "RFC3339Nano",
            type: "constant",
            info: "",
            detail: "RFC3339Nano constant representing the RFC3339Nano time format",
            apply: "RFC3339Nano",
            returnType: "string",
            source: "go_constant",
        },
        {
            label: "RFC822",
            type: "constant",
            info: "",
            detail: "RFC822 constant representing the RFC822 time format",
            apply: "RFC822",
            returnType: "string",
            source: "go_constant",
        },
        {
            label: "RFC822Z",
            type: "constant",
            info: "",
            detail: "RFC822Z constant representing the RFC822Z time format",
            apply: "RFC822Z",
            returnType: "string",
            source: "go_constant",
        },
        {
            label: "RFC850",
            type: "constant",
            info: "",
            detail: "RFC850 constant representing the RFC850 time format",
            apply: "RFC850",
            returnType: "string",
            source: "go_constant",
        },
        {
            label: "RubyDate",
            type: "constant",
            info: "",
            detail: "RubyDate constant representing the Ruby date format",
            apply: "RubyDate",
            returnType: "string",
            source: "go_constant",
        },
        {
            label: "Saturday",
            type: "constant",
            info: "",
            detail: "Saturday constant representing the Saturday weekday",
            apply: "Saturday",
            returnType: "Weekday",
            source: "go_constant",
        },
        {
            label: "Second",
            type: "constant",
            info: "",
            detail: "Time constant representing one second",
            apply: "Second",
            returnType: "time.Duration",
            source: "go_constant",
        },
        {
            label: "September",
            type: "constant",
            info: "",
            detail: "September constant representing the September month",
            apply: "September",
            returnType: "time.Month",
            source: "go_constant",
        },
        {
            label: "Stamp",
            type: "constant",
            info: "",
            detail: "Stamp constant representing the Stamp time format",
            apply: "Stamp",
            returnType: "string",
            source: "go_constant",
        },
        {
            label: "StampMicro",
            type: "constant",
            info: "",
            detail: "StampMicro constant representing the StampMicro time format",
            apply: "StampMicro",
            returnType: "string",
            source: "go_constant",
        },
        {
            label: "StampMilli",
            type: "constant",
            info: "",
            detail: "StampMilli constant representing the StampMilli time format",
            apply: "StampMilli",
            returnType: "string",
            source: "go_constant",
        },
        {
            label: "StampNano",
            type: "constant",
            info: "",
            detail: "StampNano constant representing the StampNano time format",
            apply: "StampNano",
            returnType: "string",
            source: "go_constant",
        },
        {
            label: "Sunday",
            type: "constant",
            info: "",
            detail: "Sunday constant representing the Sunday weekday",
            apply: "Sunday",
            returnType: "Weekday",
            source: "go_constant",
        },
        {
            label: "Thursday",
            type: "constant",
            info: "",
            detail: "Thursday constant representing the Thursday weekday",
            apply: "Thursday",
            returnType: "Weekday",
            source: "go_constant",
        },
        {
            label: "TimeOnly",
            type: "constant",
            info: "",
            detail: "TimeOnly constant representing the TimeOnly time format",
            apply: "TimeOnly",
            returnType: "string",
            source: "go_constant",
        },
        {
            label: "Tuesday",
            type: "constant",
            info: "",
            detail: "Tuesday constant representing the Tuesday weekday",
            apply: "Tuesday",
            returnType: "Weekday",
            source: "go_constant",
        },
        {
            label: "UnixDate",
            type: "constant",
            info: "",
            detail: "UnixDate constant representing the Unix date format",
            apply: "UnixDate",
            returnType: "string",
            source: "go_constant",
        },
        {
            label: "UTC",
            type: "constant",
            info: "",
            detail: "Time constant representing UTC location",
            apply: "UTC",
            returnType: "time.Location",
            source: "go_constant",
        },
        {
            label: "Wednesday",
            type: "constant",
            info: "",
            detail: "Wednesday constant representing the Wednesday weekday",
            apply: "Wednesday",
            returnType: "Weekday",
            source: "go_constant",
        },
        {
            label: "Date",
            type: "method",
            info: "Returns the time corresponding to yyyy-mm-dd hh:mm:ss + nsec nanoseconds",
            detail: "(year int, month Month, day, hour, min, sec, nsec int, loc *Location) => time.Time",
            apply: applyFunction("Date(year, month, day, hour, min, sec, nsec, time.UTC)", 5, 9),
            returnType: "time.Time",
            source: "go_function",
        },
        {
            label: "FixedZone",
            type: "method",
            info: "Returns a Location that always uses the given zone name and offset (seconds east of UTC).",
            detail: "(name string, offset int) => *time.Location",
            apply: applyFunction('FixedZone("UTC-8", -8*60*60)', 11, 16),
            returnType: "time.Location",
            source: "go_function",
        },
        {
            label: "LoadLocation",
            type: "method",
            info: "Returns the name of the location",
            detail: "(locationName string) => time.Location",
            apply: applyFunction("LoadLocation(locationName)", 13, 25),
            returnType: "time.Location",
            source: "go_function",
        },
        {
            label: "LoadLocationFromTZData",
            type: "method",
            info: "Returns a Location with the given name initialized from the IANA Time Zone database-formatted data. The data should be in the format of a standard IANA time zone file (for example, the content of /etc/localtime on Unix systems).",
            detail: "(locationName string, data []byte) => time.Location",
            apply: applyFunction("LoadLocation(locationName, data)", 13, 25),
            returnType: "time.Location",
            source: "go_function",
        },
        {
            label: "Now",
            type: "method",
            info: "Get the current time",
            detail: "() => time.Time",
            apply: "Now()",
            returnType: "time.Time",
            source: "go_function",
        },
        {
            label: "Parse",
            type: "method",
            info: "Parses a formatted string and returns the time value it represents",
            detail: "(layout: string, value: string) => time.Time",
            apply: applyFunction('Parse(time.RFC3339, "2010-01-02T15:04:05Z")', 6, 18),
            returnType: "time.Time",
            source: "go_function",
        },
        {
            label: "ParseDuration",
            type: "method",
            info: "Parse a duration string",
            detail: "(s string) => time.Duration",
            apply: applyFunction('ParseDuration("1h30m")', 15, 21),
            returnType: "time.Duration",
            source: "go_function",
        },
        {
            label: "ParseInLocation",
            type: "method",
            info: "Parses a formatted string and returns the time value it represents in a specific location",
            detail: "(layout: string, value: string, loc *Location) => time.Time",
            apply: applyFunction('ParseInLocation(time.RFC3339, "2012-Jul-09", time.UTC)', 16, 28),
            returnType: "time.Time",
            source: "go_function",
        },
        {
            label: "Since",
            type: "method",
            info: "Calculate the duration since a specific time",
            detail: "(t Time) => time.Duration",
            apply: applyFunction("Since(t1)", 6, 8),
            returnType: "time.Duration",
            source: "go_function",
        },
        {
            label: "Sleep",
            type: "method",
            info: "Sleep for a duration",
            detail: "(d Duration) => void",
            apply: applyFunction("Sleep(time.Second *5);", 6, 20),
            returnType: "void",
            source: "go_function",
        },
        {
            label: "Until",
            type: "method",
            info: "Calculate the duration until a specific time",
            detail: "(t Time) => time.Duration",
            apply: applyFunction("Until(Now())", 6, 20),
            returnType: "time.Duration",
            source: "go_function",
        },
        {
            label: "Add",
            type: "method",
            info: "Add a duration to the time",
            detail: "(d Duration) => time.Time",
            apply: applyFunction("Add(time.Hour)", 4, 13),
            returnType: "time.Time",
            source: "go_method",
        },
        {
            label: "AddDate",
            type: "method",
            info: "Add a date to the time",
            detail: "(years int, months int, days int) => time.Time",
            apply: applyFunction("AddDate(1, 0, 0)", 8, 8),
            returnType: "time.Time",
            source: "go_method",
        },
        {
            label: "After",
            type: "method",
            info: "Check if the time is after another time",
            detail: "(t Time) => boolean",
            apply: applyFunction("After(t1)", 6, 12),
            returnType: "boolean",
            source: "go_method",
        },
        {
            label: "Before",
            type: "method",
            info: "Check if the time is before another time",
            detail: "(t Time) => boolean",
            apply: applyFunction("Before(t1)", 7, 13),
            returnType: "boolean",
            source: "go_method",
        },
        {
            label: "Clock",
            type: "method",
            info: "Returns the hour, minute, and second within the day specified by t.",
            detail: "() => Array<number>",
            apply: "Clock(t1)",
            returnType: "Array<number>",
            source: "go_method",
        },
        {
            label: "Compare",
            type: "method",
            info: "Compares the time instant t with t1. If t is before u, it returns -1; if t is after u, it returns +1; if they're the same, it returns 0.",
            detail: "(t Time) => number",
            apply: applyFunction("Compare(t1)", 8, 14),
            returnType: "number",
            source: "go_method",
        },
        {
            label: "Date",
            type: "method",
            info: "Returns the year, month, and day in the time instant t.",
            detail: "() => [year int, month int, day int]",
            apply: "Date()",
            returnType: "Array<number>",
            source: "go_method",
        },
        {
            label: "Day",
            type: "method",
            info: "Returns the day in the time instant t.",
            detail: "() => number",
            apply: "Day()",
            returnType: "number",
            source: "go_method",
        },
        {
            label: "Equal",
            type: "method",
            info: "Check if the time is equal to another time",
            detail: "(t Time) => boolean",
            apply: applyFunction("Equal(t1)", 6, 12),
            returnType: "boolean",
            source: "go_method",
        },
        {
            label: "Format",
            type: "method",
            info: "Format the time according to a layout string",
            detail: "(layout string) => string",
            apply: applyFunction('Format("2006-01-02T15:04:05Z07:00")', 8, 33),
            returnType: "string",
            source: "go_method",
        },
        {
            label: "Hour",
            type: "method",
            info: "Returns  the hour within the day specified by t, in the range [0, 23].",
            detail: "() => number",
            apply: "Hour()",
            returnType: "number",
            source: "go_method",
        },
        {
            label: "ISOWeek",
            type: "method",
            info: "Returns the ISO 8601 week number",
            detail: "() => [year int, week int]",
            apply: "ISOWeek()",
            returnType: "Array<number>",
            source: "go_method",
        },
        {
            label: "In",
            type: "method",
            info: "Returns the time in a specific location",
            detail: "(loc *Location) => time.Time",
            apply: applyFunction("In(time.UTC)", 3, 11),
            returnType: "time.Time",
            source: "go_method",
        },
        {
            label: "IsDST",
            type: "method",
            info: "Check if the time is in Daylight Saving Time",
            detail: "() => boolean",
            apply: "IsDST()",
            returnType: "boolean",
            source: "go_method",
        },
        {
            label: "IsZero",
            type: "method",
            info: "Check if the time is zero",
            detail: "() => boolean",
            apply: "IsZero()",
            returnType: "boolean",
            source: "go_method",
        },
        {
            label: "Local",
            type: "method",
            info: "Returns t with the location set to local ",
            detail: "() => time.Time",
            apply: "Local()",
            returnType: "time.Time",
            source: "go_method",
        },
        {
            label: "Location",
            type: "method",
            info: "Returns the location of the time",
            detail: "() => *time.Location",
            apply: "Location()",
            returnType: "time.Location",
            source: "go_method",
        },
        {
            label: "Minute",
            type: "method",
            info: "Returns the minute within the hour specified by t, in the range [0, 59].",
            detail: "() => number",
            apply: "Minute()",
            returnType: "number",
            source: "go_method",
        },
        {
            label: "Month",
            type: "method",
            info: "Returns the month in the time instant t.",
            detail: "() => time.Month",
            apply: "Month()",
            returnType: "time.Month",
            source: "go_method",
        },
        {
            label: "Nanosecond",
            type: "method",
            info: "Returns the nanosecond offset within the second specified by t, in the range [0, 999999999].",
            detail: "() => number",
            apply: "Nanosecond()",
            returnType: "number",
            source: "go_method",
        },
        {
            label: "Round",
            type: "method",
            info: "Return the result of rounding t to the nearest multiple of d (since the zero time).",
            detail: "(d Duration) => time.Time",
            apply: applyFunction("Round(time.Minute)", 6, 17),
            returnType: "time.Time",
            source: "go_method",
        },
        {
            label: "Second",
            type: "method",
            info: "Returns the second within the minute specified by t, in the range [0, 59].",
            detail: "() => number",
            apply: "Second()",
            returnType: "number",
            source: "go_method",
        },
        {
            label: "Sub",
            type: "method",
            info: "Subtract a duration from the time",
            detail: "(t Time) => time.Duration",
            apply: applyFunction("Sub(time.Now())", 4, 14),
            returnType: "time.Duration",
            source: "go_method",
        },
        {
            label: "UTC",
            type: "method",
            info: "Returns t with the location set to UTC.",
            detail: "() => time.Time",
            apply: "UTC()",
            returnType: "Time",
            source: "go_method",
        },
        {
            label: "Unix",
            type: "method",
            info: "Returns t as a Unix time, the number of seconds elapsed since January 1, 1970 UTC.",
            detail: "() => int64",
            apply: "Unix()",
            returnType: "int64",
            source: "go_method",
        },
        {
            label: "UnixMicro",
            type: "method",
            info: "Returns t as a Unix time, the number of microseconds elapsed since January 1, 1970 UTC.",
            detail: "() => int64",
            apply: "UnixMicro()",
            returnType: "int64",
            source: "go_method",
        },
        {
            label: "UnixMilli",
            type: "method",
            info: "Returns t as a Unix time, the number of milliseconds elapsed since January 1, 1970 UTC.",
            detail: "() => int64",
            apply: "UnixMilli()",
            returnType: "int64",
            source: "go_method",
        },
        {
            label: "Weekday",
            type: "method",
            info: "Returns the day of the week specified by t.",
            detail: "() => Weekday",
            apply: "Weekday()",
            returnType: "Weekday",
            source: "go_method",
        },
        {
            label: "Year",
            type: "method",
            info: "Returns the year in the time instant t.",
            detail: "() => number",
            apply: "Year()",
            returnType: "number",
            source: "go_method",
        },
        {
            label: "YearDay",
            type: "method",
            info: "Returns the day of the year specified by t, in the range [1, 366].",
            detail: "() => number",
            apply: "YearDay()",
            returnType: "number",
            source: "go_method",
        },
        {
            label: "Zone",
            type: "method",
            info: "computes the time zone in effect at time t, returning the abbreviated name of the zone (such as 'CET') and its offset in seconds east of UTC.",
            detail: "() => [name string, offset int]",
            apply: "Zone()",
            returnType: "[string, int]",
            source: "go_method",
        },
        {
            label: "ZoneBounds",
            type: "method",
            info: "Returns the boundaries of the time zone specified by t.",
            detail: "() => [start time.Time, end time.Time]",
            apply: "ZoneBounds()",
            returnType: "[time.Time, time.Time]",
            source: "go_method",
        },
        {
            label: "Duration",
            type: "method",
            info: "Calculate the resulting duration",
            detail: "(duration Duration) => time.Duration",
            apply: applyFunction("CalculateDuration(2 * time.Hour + 30 * time.Minute)", 18, 50),
            returnType: "time.Duration",
            source: "osi4iot",
        },
        {
            label: "GetCurrentTime",
            type: "method",
            info: "Get the current time in RFC3339 format",
            detail: "() => string",
            apply: "GetCurrentTime();",
            returnType: "string",
            source: "osi4iot",
        },
        {
            label: "GetParseError(layout, value, layoutElem, valueElem, message string) *time.ParseError",
            type: "method",
            info: "Returns a ParseError for the given parameters.",
            detail: "(layout, value, layoutElem, valueElem, message string) => *time.ParseError",
            apply: applyFunction("GetParseError(layout, value, layoutElem, valueElem, message)", 14, 20),
            returnType: "time.ParseError",
            source: "osi4iot",
        },
        {
            label: "GetTimeFromUnix",
            type: "method",
            info: "Returns the local Time corresponding to the given Unix time, sec seconds and nsec nanoseconds since January 1, 1970 UTC.",
            detail: "(sec int64, nsec int64) => time.Time",
            apply: applyFunction("GetTimeFromUnix(1609459200, 0)", 16, 26),
            returnType: "time.Time",
            source: "osi4iot",
        },
        {
            label: "GetTimeFromUnixMicro",
            type: "method",
            info: "Returns the local Time corresponding to the given Unix time, usec microseconds since January 1, 1970 UTC.",
            detail: "(usec int64) => time.Time",
            apply: applyFunction("GetTimeFromUnixMicro(1257894000000000, 0)", 21, 37),
            returnType: "time.Time",
            source: "osi4iot",
        },
        {
            label: "GetTimeFromUnixMilli",
            type: "method",
            info: "Returns the local Time corresponding to the given Unix time, msec milliseconds since January 1, 1970 UTC.",
            detail: "(msec int64) => time.Time",
            apply: applyFunction("GetTimeFromUnixMilli(1257894000000)", 21, 34),
            returnType: "time.Time",
            source: "osi4iot",
        },
    ],
    instances: [
        {
            label: "time",
            declaration: "const time = go.Time()",
            insert: "time = go.Time();",
            info: "Create Time instance",
        },
    ],
};
