FROM arm64v8/node:12-slim

COPY flows_cred.json /data
COPY flows.json /data
COPY settings.js /data
COPY entry_script.sh /src/scripts/entry_script.sh
RUN chmod +x /src/scripts/entry_script.sh

RUN npm install node-red-contrib-re-postgres

ENTRYPOINT ["/src/scripts/entry_script.sh"]