FROM nodered/node-red

RUN npm install node-red-dashboard \
    npm install node-red-contrib-schedex \
    npm install node-red-contrib-yield \
    npm install node-red-contrib-re-postgres \
    npm install node-red-contrib-uuid \
    npm install node-red-node-email \
    npm install node-red-contrib-users
    # npm install node-red-node-pushover \
    # npm install node-red-contrib-ttn \
    # npm install node-red-contrib-timeout \
    # npm install node-red-contrib-power-monitor \
    # npm install node-red-contrib-blynk-ws \
    # npm install node-red-contrib-telegrambot \
    # npm install node-red-node-mysql \
    # npm install node-red-contrib-influxdb \




