FROM arm64v8/node:12-slim

COPY --chown=node-red:node-red flows_cred.json /data
COPY --chown=node-red:node-red flows.json /data
COPY --chown=node-red:node-red settings.js /data
COPY entry_script.sh /src/scripts/entry_script.sh
USER root
RUN chmod +x /src/scripts/entry_script.sh
USER node-red

RUN npm install node-red-contrib-re-postgres

ENTRYPOINT ["/src/scripts/entry_script.sh"]